### ISSUE TITLE
Debugging Pod->Node->Actual Machine Very Onerous

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/kraken-lib#101]
There is no easy correlation between a kubernetes Node and the actual EC2 instance it represents.
When debugging a Pod issue that requires validating items directly on the EC2 instance (and docker running there)...it is extremely onerous to determine the actual ssh values needed to check that machine.

**Comment by coffeepac** [comment]
would a combination of making sure the generated ssh config file is complete with node tagging be sufficient?  that way you could do a 'get nodes' and see the k2 tag 'clusterNode-2' and ssh to it.

**Comment by coffeepac** [comment]
@samba can you please attach a link to your script here and we'll see if its a good thing for k2-tools to ship with.

**Comment by samba** [comment]
As a temporary stash of my utility script...
https://github.com/samba/k2-tools/blob/util/cluster_interrogate_nodes/util/list_pod_nodes_status.sh

@mikeln @coffeepac What adaptation is necessary to make this usable for our work? 

- The arguments to the script positional only.
- Requires `coreutils` package.

(It was a hack...)

**Comment by mikeln** [comment]
hmm... maybe none?  if it works (haven't tried it yet).

**Comment by coffeepac** [comment]
there is a PR incoming that introduces a bastion-elb node type #759, this script (specifically the external DNS function) may need to be updated to deal with this.
