### ISSUE TITLE
upgraded master nodes fail to connect to etcd

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#1024]
Configs with the split etcd nodes fail to connect to etcd as the hostname has changed to `etcd.etcd.<cluster name>.internal` in kraken-lib but the old nodes still have the original hostname `etcd.<cluster name>.internal`.

**Comment by joejulian** [comment]
One workaround is to create the missing hostnames in route53 as CNAME entries that point to the old hostnames.

**Comment by davidewatson** [comment]
Another area where etcd DNS names are problematic: `ansible/roles/kraken.nodePool/kraken.nodePool.etcd/templates/etcd.units.kraken-etcd-ssl.part.jinja2`:

```
     --set-env=SERVICE_DNS_NAME=etcd.{{ cluster_node_tuple.1.name }}.{{ cluster_node_tuple.0.name }}.internal \
     --set-env=HOST_DNS_NAME=*.{{ cluster_node_tuple.1.name }}.{{ cluster_node_tuple.0.name }}.internal \
     --set-env=EVENTS_SERVICE_DNS_NAME=etcdevents.{{ cluster_node_tuple.1.name }}.{{ cluster_node_tuple.0.name }}.internal \
     --set-env=EVENTS_HOST_DNS_NAME=*.etcdevents.{{ cluster_node_tuple.1.name }}.{{ cluster_node_tuple.0.name }}.internal \
```

The `etcdevents` name should not be hardcoded.
