### ISSUE TITLE
update gitlab.ci file to allow for specifying which version of kraken-tools to use

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#1040]
there is currently no way to specify what version of the kraken-tools image to use as the base image for kraken-lib.  

this was being done via the file `kraken-lib/build-scripts/docker-update.sh` in the jenkinsfile world.  we may be able to use a more recent version of docker and pass this value in as an env var directly to the dockerfile, I don't remember what bug prevented us from doing that before.

anyway!  we need this back.

**Comment by leahnp** [comment]
@coffeepac To make sure I understand this issue completely - we want to have the ability to dynamically change: `KRAKEN_TOOLS: "quay.io/samsung_cnct/kraken-tools:latest"` the "latest" tag on line 25 in our current .gitlab-ci.yml?

**Comment by coffeepac** [comment]
Yes.  If we are unable to specify a specific version of kraken tools then
we cant be sure of what we are shipping.

**Comment by leahnp** [comment]
@coffeepac why wouldn't we want to just update the KRAKEN_TOOLS image version directly in the .gitlab-ci.yml? I think I am not understanding the use case for dynamically requiring a different version, other than what is set in the .gitlab-ci.yml already.

**Comment by coffeepac** [comment]
the version of KRAKEN_TOOLS specified in the gitlab configuration file determines what image to use for testing/validating kraken-lib.  however, when we go to build the kraken-lib image to push to quay, we execute 'docker build' which will use the dockerfile in kraken-lib/docker.

we need to be altering the dockerfile
