### ISSUE TITLE
release process is broken

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#1050]
latest attempt to release kraken-lib (tag v0.13, CI run: https://git.cnct.io/common-tools/samsung-cnct_kraken-lib/-/jobs/6581) is failing because the gitlab runner can't find the script 'build-scripts/docker-update.sh'.  

it is not immediately obvious to me why this is failing as that path should be available.

**Comment by philoserf** [comment]
Hmm. Usually this is because the PWD is not what we expected. Also, another item reference in the config using the `./dir/script` while ths one uses ’dir/script’. Usually that shouldn't matter. I’d consider dropping an `echo $PWD` in just ahead of the call to the acript..

**Comment by coffeepac** [comment]
fixed.
