### ISSUE TITLE
save remote state of config files as a configmapper/etcd/secret?

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#125]
k2 should save the stateful file to the hosting provider (or baremetal) so there is a redundant log of where to find state for a specific cluster that isn't on the creating machine.

**Comment by joejulian** [comment]
What about putting this inside the cluster? minio s3 store maybe?

**Comment by coffeepac** [comment]
interesting idea!  if we're using a native cluster resource maybe we could use etcd?  that may be terrible though, I don't know what the size restrictions are on etcd keys.  or size recommendations at least.  I know zk gets cranky if the key data is over 1k.

**Comment by venezia** [comment]
You're safe with etcd.  But why not just (maybe) do it a bit less hacky and say create a k2-management pod that you interact with (and this stores it into etcd)
