### ISSUE TITLE
CI notifications go nowhere

### ISSUE THREAD

**Issue by spiffxp** [samsung-cnct/kraken-lib#135]
I opened the following PR: https://github.com/samsung-cnct/k2/pull/134
I was not notified that a CI job had been started: https://pipelet.kubeme.io/job/k2-pr/126/

We used to use slack for this.  Should we just be using github commit status and its details at this point?

**Comment by coffeepac** [comment]
this should be going to ping-jenkins.

is a general note in there sufficient or would you want to be tagged in it?

**Comment by spiffxp** [comment]
General note in a Jenkins channel sgtm. Much like I would assume all GitHub pings to land in our GitHub slack channel.

**Comment by spiffxp** [comment]
Same deal with https://pipelet.kubeme.io/job/k2-e2e-aws-k8s-conformance/78/

**Comment by spiffxp** [comment]
That PR (or its manual application) apparently didn't work, still not seeing any notifications

**Comment by coffeepac** [comment]
this was originally about pipelet it should be applied to new jenkins as well

**Comment by coffeepac** [comment]
closing this for now.  if we want gitlab to do this we should open a new issue for that.
