### ISSUE TITLE
Include kubernetes dashboard in default services list

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#139]
super easy, just add it.

**Comment by coffeepac** [comment]
There may be a problem with including this by default in the config.

**Comment by leahnp** [comment]
https://github.com/samsung-cnct/k2/pull/225

**Comment by leahnp** [comment]
Waiting on RBAC support to make dashboard secure: https://github.com/kubernetes/dashboard/issues/964
