### ISSUE TITLE
CoreOS/MaaS integration

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#143]
can we install CoreOS ISOs onto MaaS nodes?  Its unclear at the moment!

**Comment by coffeepac** [comment]
CoreOS is not listed as a supported operating system.  

It appears that only paying users can use an OS other then an ubuntu variant.  This isn't great.

**Comment by coffeepac** [comment]
We can not install CoreOS via MaaS right now.  @countspongebob is going to try and see what can be done to give us access to do this.

**Comment by coffeepac** [comment]
or: http://askubuntu.com/questions/759109/maas-2-0-importing-custom-images-does-not-work 

back to ToDo for this issue

**Comment by coffeepac** [comment]
this is 100% possible:  http://maas.ubuntu.com/docs/os-support.html?highlight=custom%20image

except that CoreOS is an immutable OS and that doesn't play with MaaS.  Should be available at the same time that ubuntu core is in April.  Mothballing until then.

**Comment by countspongebob** [comment]
We are expecting to see something from Canonical earlier than April... April is "GA". Expecting an update from them in the next week. Expecting that whatever solution they come up with with handle CoreOS and Ubuntu core.

**Comment by distributorofpain** [comment]
Any news on this?  Would like to use MaaS to rollout a coreOS setup.  They just released Matchbox, which i may end up using in place.

**Comment by coffeepac** [comment]
@distributorofpain we had to let this drop for a bit.  We're planning on picking it back up in July/August.

**Comment by countspongebob** [comment]
@distributorofpain Can you say a bit more about your use case?
