### ISSUE TITLE
Add cluster autoscaling support

### ISSUE THREAD

**Issue by venezia** [samsung-cnct/kraken-lib#150]
On cloud environments (AWS, GCE, Azure) adding additional nodes can be done through APIs.

Having a right-sized kubernetes environment would reduce costs while at the same to be responsive to the cluster's need for additional hardware when appropriate.

Kubernetes supports cluster autoscaling for GCE, GKE and AWS.  We should have this be an option in K2.  https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler for reference

**Comment by sostheim** [comment]
/cc @samba - this came up recently in a context for your work did it not?
I've also had recent inquiries for this feature in reference to supporting node pool dynamic sizing.

**Comment by samba** [comment]
Similar inquiries on my end as well, in essence. 

I think the need is well-understood: resource pressure driving the provider-automated spin-up of new nodes (etc). As I understand it, the biggest challenge is testing and QA, rather than actually implementing the change at the config layer.

**Comment by coffeepac** [comment]
the old hold up was preventing terraform from wiping out changes that the autoscaler made to nodepool size.  we can fix that though by excluding nodepool size as a reason to update an ASG unless a new 'force' flag is set.  its a bit hacky (will be adding more conditional-ness to the terraform templates) but we need some additional channel of communication so we can let kubernetes manage the nodepool size until the kraken operator changes their mind.

if we do this, I believe it opens up a path for a client, right?

**Comment by samba** [comment]
@coffeepac yes, it opens up some client adoption paths. 

I haven't looked into the management config within Kubernetes, but within Terraform, isn't it really just focused on the [ASG definition][1]? Seems like fitting to that scale-up capability alone would be a good start.


[1]: https://github.com/samsung-cnct/kraken-lib/blob/master/ansible/roles/kraken.provider/kraken.provider.aws/templates/v1.5/kraken.provider.aws.module.node.tf.jinja2#L143

**Comment by davidewatson** [comment]
This shows some promise. https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws

> Cluster autoscaler is not zone aware (for now), so if you wish to span multiple availability zones in your autoscaling groups beware that cluster autoscaler will not evenly distribute them. For more information, see https://github.com/kubernetes/contrib/pull/1552#r75532949.

Which maybe isn't so bad. Many questions...

**Comment by leahnp** [comment]
Note: Cluster Autoscaler v1.0 which is compatible with K8s v1.8 does not support Azure [PR](https://github.com/kubernetes/autoscaler/pull/229)

**Comment by leahnp** [comment]
For this work should we limit cluster auto-scaling to only cluster nodes? @coffeepac

**Comment by leahnp** [comment]
Considering using the chart: https://github.com/kubernetes/charts/tree/master/stable/cluster-autoscaler

Currently tweaking IAM policy to allow autoscaling.

**Comment by coffeepac** [comment]
if its possible we should be trying to only autoscale cluster nodepools

**Comment by leahnp** [comment]
We will need to use different versions of the addon for backwards compatibility: https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler

**Comment by leahnp** [comment]
I have a CA deployment that works to add nodes, but when I try to scale down I get the error: 
` No candidates for scale down`
I think this is due to the fact canal and kube-proxy are running on the nodes. The issue is documented: https://github.com/kubernetes/contrib/issues/2552

I am looking into PDB referenced here as a possible fix: https://github.com/kubernetes/autoscaler/issues/350

**Comment by leahnp** [comment]
Actually...I think `scale down` just worked, it just took a while. Scratch the prior comment.

**Comment by leahnp** [comment]
@coffeepac do we want to spin this up with the default config? Similar to `heapster` or do we want to deploy as an optional addon (perhaps with a flag?).

**Comment by coffeepac** [comment]
part of default config. 

is there anything to do for GKE clusters?

**Comment by leahnp** [comment]
I haven't tested it yet, but from the community commentary regarding the `cluster autoscaling` addon - it supposedly works better on GKE. So I am assuming we will be able to offer CA for both AWS and GKE.

**Comment by coffeepac** [comment]
huzzah!  thanks!

**Comment by davidewatson** [comment]
Do we need to disallow nodePool size changes when the auto-scaler is used? I think it could be done by adding a check to the compatibility module. Or should we disable changing the size of nodePools from kraken completely? I think the latter would be easier to support, but I can see arguments against it.

**Comment by coffeepac** [comment]
spoke with @leahnp out of band and we are going to do the following:
- ignore any changes to the nodepool if autoscaling is enabled
- file a feature request for 'allow the cluster operator to force the nodepool size to a specific number even if autoscaling is enabled'.  There are a bunch of operational questions about what happens and I'm not sure its a feature anyone wants.

**Comment by leahnp** [comment]
There does not seem to be a stable Helm chart for cluster-autoscaling on GKE

**Comment by leahnp** [comment]
Good tip from the GKE documentation on cluster-autoscaling:

```Keep in mind that when resources are deleted or moved in the course of autoscaling your cluster, your services can experience some disruption. For example, if your service consists of a controller with a single replica, that replica's Pod might be restarted on a different node if its current node is deleted. Before enabling autoscaling, ensure that your services can tolerate potential disruption.

Note: You can make your services more disruption-tolerant by running them as part of a controller with multiple replicas, such as a Deployment.```

**Comment by leahnp** [comment]
Another point to keep in my re: cluster auto-scaling on GKE: 

> Cluster autoscaler does not track labels manually added after initial cluster or node pool creation. Nodes created by cluster autoscaler are assigned labels specified with --node-labels at the time of node pool creation.
