### ISSUE TITLE
Explore launching kubernetes cluster on ubuntu 16.04 using K2

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#157]
The output of this ticket is one of two things:
- a PR to k2 with the changes needed to allow using ubuntu 16.04 as a base OS
- a set of tickets that specify the work needed to enable k2 to launch kubernetes on ubuntu 16.04

**Comment by coffeepac** [comment]
we are leveraging the coreos cloud-init customizations heavily in k2.  we will need to unpack those to work on ubuntu.  not hard, but will require a fair amount of template re-writing.

if possible, we should see if the ubuntu cloud-init format works on coreos.  bummer to not be using coreos nicities but it'd be even better to only have one set of templates.

**Comment by coffeepac** [comment]
made an ubuntu image in us-east-1 that has rkt installed.  going to start walking through the cloud config differences now.

**Comment by coffeepac** [comment]
two notes:
1. cloud init only seems to run on this ubuntu 16.04 ami on initial boot, not on subsequent boots.  means I either have to figure out how to set cloud-init to run on the next boot OR I can't create derivative AMIs and expect cloud init to work
2. failing to set the file owner:group to root:root causes the write_files module to not write to a directory that is only writable by root.  okay.

But this works and systemd is picking up the file as expected.  I chose a unit file that has a dependency so its not starting but next up is making sure that these rkt services start as expected on system boot.  Tomorrow's job.

**Comment by coffeepac** [comment]
Almost done with other higher-priority work.  Expect to get back to this today or tomorrow.

**Comment by coffeepac** [comment]
team focus shift from bare metal to CI.  Will get back to this in awhile.  for now going to unassign and push to Backlog.

**Comment by coffeepac** [comment]
don't lose this link:  http://dustymabe.com/2015/08/03/installingstarting-systemd-services-using-cloud-init/

**Comment by coffeepac** [comment]
@joejulian do you want to grab this issue for joyent work?  if so, push it back to p1 and slap a joyent label on it

**Comment by joejulian** [comment]
This will require a terraform provider in place of `terraform-provider-coreosbox`. I'm thinking of making one that's just `terraform-provider-distro-image` that can be extended to handle multiple distros.

**Comment by coffeepac** [comment]
+1 to creating a new plugin, or just evolving coreosbox to support multiple OSes.

**Comment by joejulian** [comment]
That's my plan, more or less. There is a bit that needs restructured but I'll reuse as much of the coreosbox code as possible.

**Comment by joejulian** [comment]
Blocked by https://github.com/samsung-cnct/terraform-provider-distro-image/issues/2

**Comment by coffeepac** [comment]
getting the configuration section written in a way to accept an arbitrary set of key/values used to be very difficult.  may be easier now (I haven't tried to do it in about a year).  if you need help lemme know, at one point I was rather knowledgeable of terraform types.

**Comment by coffeepac** [comment]
`#cloud-config
runcmd:
- ["wget", "https://github.com/coreos/rkt/releases/download/v1.21.0/rkt_1.21.0-1_amd64.deb"]
- ["sudo", "dpkg", "-i", "rkt_1.21.0-1_amd64.deb"]
`

@joejulian the above is a snippet I was running originally to get rkt installed so I didn't have to mess with that part of K2 right off the bat.  not sure if its useful to you or now but so you don't have to create that bit of cloud-config

**Comment by joejulian** [comment]
With the new dict method of creating cloud-config, this problem becomes much simpler.

The cloud_config/units.yaml is now used for creating coreos-specific entries for systemd units. By replacing this one file with another that does write_file and 2 commands (systemctl daemon-reload, and start) this becomes pretty trivial.

Closing this research issue.
