### ISSUE TITLE
etcd node upgrade/downgrade

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#232]
how do we upgrade and downgrade an etcd cluster in place?  does the process differ for major vs minor versions?   is this something that can be automated?

**Comment by coffeepac** [comment]
is this best handled by using the CoreOS etcd operator?

**Comment by spiffxp** [comment]
https://github.com/kubernetes/kubernetes/issues/40636 just to give you some breadcrumbs you may already have

there are scripts to upgrade etcd2->etcd3 (and vice-versa) that are being exercised via ci

the results of up vs. down, master vs. 1.5 are here: https://k8s-testgrid.appspot.com/etcd-upgrades
