### ISSUE TITLE
generalize cloud config for all cloud-init implementations

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#239]
k2 currently uses a number of CoreOS specific cloud-init stanzas.  these need to be removed and replaced with general purpose stanzas that achieve the same things but are OS independent.

**Comment by coffeepac** [comment]
@Joejulan is this covered in https://github.com/samsung-cnct/k2/pull/403

**Comment by joejulian** [comment]
yes

**Comment by coffeepac** [comment]
so should we mark it as a dup and close it?

**Comment by DStorck** [comment]
@joejulian can we close this?

**Comment by joejulian** [comment]
It's not merged yet

On June 6, 2017 4:02:07 PM PDT, Deirdre Storck <notifications@github.com> wrote:
>@joejulian can we close this?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/samsung-cnct/k2/issues/239#issuecomment-306641617

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by coffeepac** [comment]
Okay, moving to InProgress and assigning it to you

**Comment by joejulian** [comment]
This requires #358

**Comment by coffeepac** [comment]
part of #157
