### ISSUE TITLE
create CI job that verifies non-supported kubernetes templates are removed

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#249]
as of https://github.com/samsung-cnct/k2/issues/222#issuecomment-284583580 we will be introducing template directories and ansible checks that should be removed when we no longer support that version.

create a CI job that checks the source code for no longer supported templates and version checks.  at this moment I am unsure how we are tracking what the supported versions of kubernetes are so that may also be something that needs to be determined here.

**Comment by leahnp** [comment]
Does "no longer supported templates" also include alpha/beta features that are no longer support with the upgrade? For example: someone is trying to upgrade, their clusters includes PetSets, the K8s version they are going to does not, would this job catch that?

**Comment by coffeepac** [comment]
no.  I'm not sure where should live, for now its 'operator beware'.  Which is kubernetes standard for alpha/beta features.  

these templates are the ones that k2 uses for landing the correct kubernetes startup configurations.
