### ISSUE TITLE
Add a CNI plugin version option to the config

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/kraken-lib#301]
Currently we hardcode the CNI plugin version. We shouldn't do this.

From ansible/roles/kraken.node/kraken.node.docker/templates/units.kubelet.part.jinja2:

```
    ExecStartPre=/usr/bin/bash -c '/usr/bin/wget https://github.com/containernetworking/cni/releases/download/v0.3.0/cni-v0.3.0.tgz -O - | sudo tar -xz -C /opt/cni/bin'
```

**Comment by coffeepac** [comment]
we have already punted on not having a CNI version discussion with Canal or something.  Can't punt again.
