### ISSUE TITLE
Create a backup of k2configs

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/kraken-lib#309]
Whenever a k2config file is changed, for example to enact an upgrade (#295), we have no way to know how it has been changed since the last k2 action. We should save the k2config used, each time, a k2 action occurs. This may provide us with necessary information as the scope of k2 management tasks grows.

This may also assist in auditability and debuggability in the future.

**Comment by gochist** [comment]
I made a PR https://github.com/samsung-cnct/kraken-lib/pull/1005 for this

**Comment by gochist** [comment]
Is this can be closed?

**Comment by coffeepac** [comment]
@gochist yes.  as a note for github, if you include a line in your PR like 'Fixes #<issue number>' when the PR is closed github with auto close the issue.
