### ISSUE TITLE
Get Sysdig-Agent Working Correctly.

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/kraken-lib#35]
Get K2 working similar to original kraken for sysdigcloud.
1) get sysdig-agent installed and running if the user specifies a sysdigcloud_access_key,  otherwise do not run the agent.
2) assume each user will have their own unique sysdigcloud_access_key associated with their sysdigcloud.com account.
3) Should run on all nodes and all control plane machines (master, apiserver, etcd, ... )

Note: originally the agent HAD to be installed in cloudconfig for it to work correctly.  Also, the key for seeing kubernetes data was having it running on the APIServer.

**Comment by mikeln** [comment]
relevant doc: https://support.sysdigcloud.com/hc/en-us/sections/200959909

**Comment by mikeln** [comment]
Old ticket (search jira for KRAK sysdig for more history): https://hanjin.atlassian.net/browse/KRAK-268

**Comment by cwazy1** [comment]
Make helm chart

**Comment by coffeepac** [comment]
if this is to be a helm chart, it should be closed and re-opened in the k2-charts repo

**Comment by mikeln** [comment]
ok... at least I still want this to work..so perhpas I will do that.

**Comment by coffeepac** [comment]
try to squeeze in for end of 0.3
