### ISSUE TITLE
Create a uuid when generating config files

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#353]
Create a uuid for a generated config file.

Check that uuid against the uuid stored in etcd or whatever we store it in to ensure the config file we're using matches the cluster we're attempting to manage.

Depends on #125

**Comment by davidewatson** [comment]
Without this, our current use of the `ec2_remote_facts` module to generate the `ssh_config` can get confused if there is more than one cluster in the same region with the same name. The result will be an `ssh_config` with instances from multiple clusters.
