### ISSUE TITLE
Move Config Readiness Bloc from Deployment to be By Cluster

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/kraken-lib#388]
Currently `readiness:` is by `deployment:` which applies the same criteria to each cluster.
It should be by cluster, since each cluster may have widely variant readiness criteria.
Move to be part of each `cluster:` config.

**Comment by davidewatson** [comment]
Per #392, if we add instead of move an (optional) readiness stanza to each cluster stanza, this becomes a non-breaking schema change.
