### ISSUE TITLE
Add common user to cloud-config

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#405]
Create a common username that we can use to log in to nodes so we don't have to have logic to choose which username to log in with for each distro. The current workaround is to just choose which username to log in with, eg. `ssh -F ~/.kraken/$mycluster/ssh_config ubuntu@etcd-1`.

**Comment by alejandroEsc** [comment]
Not sure if common user name is ideal, but I can see the draw. In addition we can map different user names per OS type. and not have to worry about the additional add/user name. The story changes a bit for custom images where i can see a client wanting their user name to be used.
