### ISSUE TITLE
v2alpha config file changes

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/kraken-lib#408]
This ticket is to collect any ideas we have for v2 of the config file schema.

**Comment by davidewatson** [comment]
From a discussion with @venezia, some things we might change in a v2 schema:

1) We have ansible code in our configuration values
2) We have terraform code in our configuration keys/values (our naming of things suddeny pivots for the convenience of terraform which is bad)
3) Some things that are in the "provider" config should be in the "node provider" config (cloudinit for example)
4) We're passing in our private key for seemingly no reason
5) The GKE key information seems to be mismashed (part of this seems to belong in provider config, not in 'keyPairs')
6) Unnecessary (imho) creation of "provider" component of keypairs
7) plurals are not consistent (sometimes plural, sometimes not)

**Comment by davidewatson** [comment]
Can DNS configuration be simplified? Within [cluster.json](https://github.com/samsung-cnct/k2/blob/master/schemas/config/v1/cluster.json) we have `dns` (client DNS configuration), `dnsConfig` (kube DNS configuration), and `customApiDns` (cf. "added ability to add custom domain name to k8s api server elb (#692)" cc8fe2f0).

**Comment by davidewatson** [comment]
Some config values (e.g. `etcdConfig.name`) must match portions of other values (e.g. `nodeConfig.mounts.path`). This should be enforced (cf. admission controllers). Ideally, there should also be a way to specifying this automatically (or at least only in one place, e.g. using `$data` JSON references or a YAML).

**Comment by davidewatson** [comment]
Notes-to-self do not belong in code nor documentation. Issues should be opened or commented on instead.

```
    "keypair": {
      "description": "Keypair for use with nodes - SHOULD BE MOVED TO NODE PROVIDER CONFIG?",
      "$ref": "keyPair.json"
    },

    "type": {
      "description": "How are nodes configured - SHOULD BE MOVED TO NODE PROVIDER CONFIG?",
      "enum": [
        "autonomous"
      ],
      "type": "string"
    },
```

**Comment by davidewatson** [comment]
`osConfig.locksmith.etcdConfig`  is mutually exlcusive of the `osConfig.locksmith.endpoint` and `osConfig.locksmith.etcd*file` options.

**Comment by davidewatson** [comment]
https://github.com/samsung-cnct/kraken-lib/issues/508

**Comment by coffeepac** [comment]
need to add a method for parsing the config file, seeing config options that are deprecated and emit a warning.
