### ISSUE TITLE
Calculate the needed resources and err if not available

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#429]
Yesterday I encountered a failure to launch a cluster on gke because we had used up all our storage quota. Frequently we encounter similar problems with AWS reaching other quotas: IAM roles, etc.

If we could calculate the resources that will be needed and compare that with quotas and usage we could fail early if bringing up the cluster is impossible.

We could use the same code for looking for resource leaks, which would allow us to improve that aspect as well.

**Comment by alejandroEsc** [comment]
Do these type of errors show clearly why/what resources are limited and therefore the task not performed? If these are clear i rather us report the issue instead of doing some calculation that can change or be wrong after the provider changes the math underneath us.

**Comment by joejulian** [comment]
No, the errors are frequently unclear or irrelevant. 

Additionally, if we can predict whether or not the cluster will come up, we (ourselves) can save money by not paying for resources we can't use.
