### ISSUE TITLE
TCME Design

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#430]
We would like to have a secure SSL Cert Distribution service.  This service should have the following properties:
 - go application
 - be able to choose between pre-formed certs retrieved from a remote location or generating certs on the fly
 - be able to read in the signing certs via Env vars ~~or k8s secret depending on deployment configuration~~ the k8s secret can be exposed as an env var
 - have an optional verification step to ensure the requesting node should get a cert

**Comment by venezia** [comment]
# Purpose of Application

The application is intended to generate certificates needed for a working TLS-enabled kubernetes cluster.

## Use Cases
1. API Server communicating with clients
2. Kubelet, Controller Manager, Scheduler, and Kube-Proxy to communicate with the API Server
3. Peer to Peer etcd connections
4. etcd server communicating with clients
5. etcd client communicating with an etcd server

## Certificate Parameters
### Configurable Lifetimes and Renewals
* Certificates should be written for a configurable time for each given use case (etcd peer to peer could be 1 year while kubelet certificates could be 30 days)
* Certificates should be able to be renewed.  Optionally a revocation trail can be established and distributed
### Different CA Authorities
Application should be able to use different CAs for each type of communication
* etcd peer <-> peer
* etcd server <-> client
* k8s API Server <-> consumer

## Kubernetes Integration
### Permissions
Application should be allowed to approve certificates and set role bindings as appropriate
### Integration with RBAC
Upon creation of certificates, bindings of the certificate to appropriate roles should be enabled if the application has been configured to talk to a kubernetes

## Cloud/IaaS Integration
The application should be able to support verification of the requester.  For example if a node requests a certificate package, the application should be query the the cloud provider API to see what type of node the requester is.  For example, a control plane machine should be able to request control plane certificates while an etcd node should be able to request peer certificates.

## External Certificate Generators
Application should be configurable to delegate certificate generation to a third party if desired

## Certificate Delivery
An optional method of delivery is to deliver the certificate to a pre-determined port on the host.  This would be to alleviate an issue where a user on the node could request a certificate.  Instead the delivery of the certificate would be done to a process listening on a privileged port.

## Logs and performance metrics
Logs of the application should be set to stdout, per 12 factor design
Metrics monitoring the health of the service should be created for prometheus

## Application location
The application should be able to live within a kubernetes cluster or outside of a kubernetes cluster.

**Comment by joejulian** [comment]
Does this satisfy these needs? https://blog.digitalocean.com/vault-and-kubernetes/

**Comment by notjames** [comment]
Just ran into this: https://github.com/letsencrypt/boulder
Looks like there would be some plumbing work around getting it installed and working, but it's a GO project and it might actually do what we want.
