### ISSUE TITLE
Update all K2 documentation to have cohesive voice and message

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/kraken-lib#436]
https://github.com/samsung-cnct/k2
https://github.com/samsung-cnct/k2cli
http://samsung-cnct.github.io/aboutK2.html

Currently the docs listed above have been written by different people at different points in K2's genesis. We need a clean sweep to insure all these docs have a clear voice and message reflecting K2's mission and current state. It should be clear what K2 is and that we recommend using K2cli to get started.

What is K2's mission today and who should these docs be written for?

K2 deploys a high-available Kubernetes cluster with a sophisticated control plane. A K2 cluster gives devOps and clusterOps professionals granular control and the ability to deploy on multiple clouds.  Our docs should explain the benefits of a 3 master node control plane, 5 ETCD cluster topology and ability to deploy in multiple availability zones.

**Comment by coffeepac** [comment]
@lostlivio has started on #437 so when that is stable we should start updating the other locations to follow that style as appropriate.
