### ISSUE TITLE
Plan http://samsung-cnct.github.io/ revamp

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/kraken-lib#437]
Redesign/modernize: http://samsung-cnct.github.io/
Create content strategy for K2.

**Comment by coffeepac** [comment]
@fiberGeneva I think this is a great issue for you, can you do a quick checkup?

**Comment by fiberGeneva** [comment]
@lostlivio is taking the lead on this one, as part of the Kubernetes Certified Partner program ... we are doing to use http://samsung-cnct.github.io/ as the landing page for the partner page link

**Comment by coffeepac** [comment]
@lostlivio as you need help, please let me know.  we will want to be updating the text on this site as the implementation changes so we'll need to make sure there's a developer friendly process for this.

**Comment by lostlivio** [comment]
@coffeepac Thanks and no problems.  I am going to update the template and some of the base information. Once i get by off from Bob/Greg on the direction I will make sure sure that we create an easy process for introducing changes (PR's that get approved, etc).
