### ISSUE TITLE
New app to hit known endpoints and create issues if new CVEs or releases

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/kraken-lib#455]
Regarding: #410 
Create an app or ... more details later

**Comment by leahnp** [comment]
If we can deploy in our production cluster [INFO](https://hanjin.atlassian.net/wiki/pages/viewpage.action?spaceKey=CoT&title=Production+Kubernetes+Cluster) and write some logs to var/log it would be very useful to test our logging pipeline.

**Comment by davidewatson** [comment]
I thought this was supposed to be done by https://github.com/samsung-cnct/beepboopbump It's unclear where we ended up with that.

**Comment by coffeepac** [comment]
beepboopbump was built for this but isn't ready, all future work should happen over there.
