### ISSUE TITLE
Kubernetes Monitoring in K2

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#477]
This is the parent issue for our monitoring work in k2.  The expected output of this issue will be:
- a clear set of minimal requirements for our monitoring solution
- a set of monitoring systems to trial

**Comment by coffeepac** [comment]
Needed metric data sources
- hardware metrics
- kubernetes style metric endpoint scraping
- kube system health (k8s nodes up, restart frequency)
- cluster resource usage over time and right now

Data should be fed into a queryable system

Must be open source

**Comment by coffeepac** [comment]
Necessary for system as a whole, maybe not here: 
- quota management

I think this would need to be an admission controller and I think one already exists but it needs to be found/written.  Putting it here so we don't build something that can't support quota management.

**Comment by spiffxp** [comment]
kube-state-metrics would be greatly appreciated https://github.com/kubernetes/kube-state-metrics/tree/master/Documentation

**Comment by spiffxp** [comment]
This may be in nice-to-have territory, but:
- ability to push metrics (eg: push data when running tests, when deploying things)
- ability to add other data sources without redeploying the monitoring system (eg: application exposes custom metrics for collection)

I don't know if this is considered orthogonal to monitoring, but would like system to support:
- ability to craft dashboards based on collected metrics, driven by source control
- ability to craft ad-hoc queries against collected metrics

**Comment by leahnp** [comment]
There are a couple monitoring projects in the /stable K8s Helm charts repo - might be cool if we could leverage something in there instead of rolling our own.

**Comment by mikeln** [comment]
I'm attempting to come up to speed here.  What monitoring tools have already been considered?
* cAdvisor
* graphana
* prometheus
* Google cloud monitoring
* sysdig
* weavescope
* wavefront
* datadog
* stackstate
* ??

**Comment by mikeln** [comment]
others from kubernetes/charts:
* Kapacitor
* kube-ops-view
* kubernetes-dashboard
* sensu / uchiwa

**Comment by mikeln** [comment]
What level of monitoring?
1) hardware (disk, cpu, network, etc )
2) OS ( systemd / rkt / docker)
3) etcd (depending how it is run)
4) kubernetes control plane
5) service apps
6) user apps
6.1)   user DBs

(I can infer some requirements from the previous comments..but clarification would be better).

**Comment by coffeepac** [comment]
at the moment I am considering no solutions to have been considered as we don't have a writeup on anything right now.  so, feel free to consider what you'd like and select a couple (exact number is up to you) to trial.  solutions must be open source though.

We are aiming to support the cluster ops role with this tooling choice, so we're looking for 1-4 and maybe 5.  Does 5 cover things like DNS and helm?

**Comment by mikeln** [comment]
yes, I think 5 would cover DNS, helm, and services deployed by helm (but not user apps deployed by helm...good luck there).

**Comment by coffeepac** [comment]
6 is explicitly not covered right now.  If it works, great, but thats not in scope.

**Comment by mikeln** [comment]
weavescope (free version)... runs as a pod+daemonset on the cluster and serves up a webpage.  worked pretty well, for a while, then locked up on me.  Detailed machine stats are not really available, only some relative usage indications of memory etc.  

Paid version gives you an online weavecloud (similar to sysdig cloud) to monitor you cluster.  Did not try that.

**Comment by mikeln** [comment]
sysdig installs a linux OS shim to monitor the machine hardware.   sysdig can be used as a CLI or via sysdigcloud (paid)  visualizer.   It is very powerful and complete...however the off network visualizer/stat aggregator may be considered a security hazard.  This supposedly is a way to run your own sysdigcloud visualizer on premises instead.

**Comment by oneilcin** [comment]
We looked at Prometheus for k8s while at HPE (and borrowed some of it's ideas for Monasca) we liked it.  What we decided:  
Cadvisor for container metrics (has Prometheus instrumentation, and I believe feeds kubelet)
Prometheus node exporter for node/vm metrics
Kubernetes API for auto-discovery of apps/services to monitor (Prometheus beta does this)
Prometheus metrics endpoints (using prometheus client lib or exporters) for application/service monitoring
Grafana for visualization - 4.0 supports alarms alerting
Another team looked at elk, and we know that fluentd can expose prometheus metrics. It would need to be explored if you can create metrics from log info using fluentd.

I saw the sysdig presentation at Monitorama and was impressed.  It uses system information (like tcpdump) to trace services (using the ports and ips) across nodes/etc.  This is good for identifying bottlenecks.  I think it would be great to support both prometheus and sysdig.

**Comment by mikeln** [comment]
Jaeger?

**Comment by mikeln** [comment]
kubectl has a `top` command now:  `top nodes`, and `top pods`

**Comment by mikeln** [comment]
kubernetes-dashboard, has some useful information.  (though the current chart is out of date and missing rbac).  Still has not authentication really, and requires "god mode" to monitor everything.  Not secure.

**Comment by alejandroEsc** [comment]
so what are our options? i suspect we are moving with prometheus and k8s dashboard? @mikeln i suspect we can restrict it since it should only be using `get` on all resources... would be nice to test it out.

**Comment by mikeln** [comment]
nice monitoring writeup by Sysdig (of course, pushing sysdig is the idea there...) https://sysdig.com/blog/monitoring-kubernetes-with-sysdig-cloud/

**Comment by mikeln** [comment]
kube-ops-view...from hits readme: 
What it is not:

> It's not a replacement for the Kubernetes Dashboard. The Kubernetes Dashboard is a general purpose UI which allows managing applications.
> It's not a monitoring solution. Use your preferred monitoring system to alert on production issues.
> It's not a operation management tool. Kubernetes Operational View does not allow interacting with the actual cluster.

Actually was unable to get it do display anything at all...very rough around the edges still.

**Comment by mikeln** [comment]
Jaeger has some interesting things: http://jaeger.readthedocs.io/en/latest/

**Comment by samba** [comment]
From our operations perspective, managing numerous customer clusters with an automated platform, I'd like to add some color:

- We'd like to rely on tooling Kraken provides "by default" in a Kraken cluster. 
- Alerting should happen on the customer cluster; initially we've supposed this would be handled by [Prometheus AlertManager][1].
- Alerting should encompass both performance metrics and logs. There appears to be [some precedent][2] for relying on Prometheus for log interpretation too.
- We'll want to be able to "push" alerting _configuration_ to the customer cluster automatically. This configuration will provide (at a minimum) API endpoints for our services to receive and route alerts to our internal ops team. Our ops automation can probably push additional deployments (i.e. pods) in conjunction with such configuration, but I'd like to leverage existing monitoring kit wherever possible.
- Our alerting configuration may need to be _in addition to_ any alert systems within the cluster that the customer directly maintains.

[1]: https://prometheus.io/docs/alerting/alertmanager/
[2]: https://github.com/kazegusuri/fluent-plugin-prometheus

**Comment by mikeln** [comment]
looks like a useful item: https://github.com/coreos/prometheus-operator

**Comment by mikeln** [comment]
Initial look seems to have all the desired monitor/alert...change config etc.

**Comment by mikeln** [comment]
still eval'ing promotheus-operator in our kraken cluster.  attempting to run it all in it's own namespace etc.

**Comment by mikeln** [comment]
real issue is getting rbac and namespacing aligned so prometheus stuff runs in its own namespace, but can still monitor everything in other namespaces, and is accessible to "outside" queries.

**Comment by alejandroEsc** [comment]
Check out @mikeln the kubernetes charts for some of these components.

**Comment by samba** [comment]
This guy has set up an impressive demo. I haven't reviewed his code yet, but he hits a lot of features with a fast deployment of Prometheus, Alertmanager and Grafana. Does RBAC automatically it seems. Worth a look?

https://github.com/camilb/prometheus-kubernetes

**Comment by mikeln** [comment]
issues with our namespace/rbac setup vs. prometheus operator setup:
from the prometheus process itself: ```time="2017-09-27T17:48:29Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:181: Failed to list *v1.Pod: User "system:serviceaccount:default:default" cannot list pods in the namespace "default". (get pods)" component="kube_client_runtime" source="kubernetes.go:75"```
even though that user does appear to have read pod access.

**Comment by mikeln** [comment]
but... coreos has also created a better one-stop setup: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus

**Comment by mikeln** [comment]
looks like he took a bit of the coreos stuff...but didn't attribute them..

**Comment by mikeln** [comment]
yes, this person did what I am in the process of doing...so it is a good reference point.

**Comment by mikeln** [comment]
finally working.  has issues with namespace changes though.  we should be able to repackage this one and use it.

**Comment by mikeln** [comment]
example: 
![mon-graf-01](https://user-images.githubusercontent.com/2447510/31039577-94d79df2-a533-11e7-8443-5602d03cb663.png)
![mon-prom-01](https://user-images.githubusercontent.com/2447510/31039579-94fdf682-a533-11e7-83eb-52a042be140f.png)
![mon-alert-01](https://user-images.githubusercontent.com/2447510/31039578-94eb6d32-a533-11e7-967a-487adeca44bc.png)

**Comment by mikeln** [comment]
Will  basic-auth ingress access be enough security on these UIs??

**Comment by coffeepac** [comment]
is basic-auth ingress access mean uid/password?  if so, how do we administer the users?

**Comment by samba** [comment]
From the Cluster Ops perspective, these dashboards will run inside the customer's cluster, but may still be valuable for us to see. We can use `kubectl port-forward` accordingly, which I believe uses TLS.

We should have other hooks into the cluster, so if users can be administered via `ConfigMap`, that might be an interesting approach for us.

In generally I don't think I'd recommend exposing these services on public interfaces (IPs) of the cluster though. If that's somehow necessary, I would rely on more than just basic auth... even digest auth would be an improvement. Is there an option for OAuth or similar integration?

**Comment by jandrake** [comment]
We need a design conversation on this. Please schedule @samba or @coffeepac ... 

Consider this:
- The source of truth for our customers needs to come from one place
- That place is a dashboard for our customer
- That dashboard will aggregate information across clusters
- We assume more than one cluster per customer
- The one place they find out the truth is an aggregate view of in-cluster information
- We MAY expose in-cluster information directly from the cluster itself but that would be an exception to our model
- The customer cluster is the source of truth feeding out systems, but not the reporting interface for the customer
- The reporting interface for out customer gets added value over time because of this

**Comment by mikeln** [comment]
@samba it may be my setup, but I have secure connection timeout issues with the `port-forward` approach (I assume I may have some TTL value incorrect in my setup).  But also, you would need to run at least 3 (maybe more) `port-forwards`.  This also limits your ability to monitor to a device that can run `kubectl`, which is probably an ok assumption...but next I'll hear.. "gee, an iPad would be a great portable monitoring solution"...which would require either a dedicated app, or, more easily, a publicly accessible https interface.

**Comment by mikeln** [comment]
@jandrake those a great things to consider. But this Issue is limited in scope to monitoring a single kraken cluster.   Multi-cluster aggregation would require a whole other set of items running "somewhere" (operations kubenetes cluster?), providing an endpoint that aggregates data from all other monitored clusters.  We should open another issue to tackle those type of requirements.

**Comment by mikeln** [comment]
Still need to fully understand the configuration setup/change of this system.

**Comment by mikeln** [comment]
So the promethues-operator controls the configuration of prometheus.  The ConfigMap for prometheus is essentially moved into a Secret.  The value in the secret is read for the config...it is the old ConfigMap base64 encoded into a field.   This does not allow the user to simply push up a new ConfigMap directly to change promethues.  Instead it is managed via the prometheus-operator...hence the move to put the actual config in a Secret, the user will never directly manipulate the config.  

Also, there are essentially 2 levels of monitoring:
1) kubernetes system low level scraping - managed by the prometheus config setup.
2) applications running in the kubernetes cluster - expose a Service + ServiceMonitor (with the correct labels) and the prometheus-operator will automatically pick up and monitor the new application.

Still investigating the actual method of prometheus scrape configuration changes.

**Comment by mikeln** [comment]
To monitor etcd, since it is outside of the cluster...   We may need to create a small headless service that is namespace concealed and protected, so that a ServiceMonitor can be created for it.   However, part of this is knowing the actual endpoint IPs of etcd cluster.

**Comment by mikeln** [comment]
using `kubectl proxy-forward` to access dashboards...tunnels through the default kubernetes ELB on aws.   The idle timeout of that is set to 60 sec.  I have not found a way to up that value temporarily or programatically.   I've had to go the AWS console and edit that timeout by hand.   This will need to be resolved.

**Comment by mikeln** [comment]
- [ ] create by hand full up monitor/alert system based on the above repos using `prometheus-operator` and all its parts.
- [ ] create monitoring setup for external etcd (nodes? and services)
- [ ] fix kubernetes timeout so `proxy-forward` is viable
- [ ] create repo for finished product
- [ ] create helm charts if possible, otherwise script the setup
