### ISSUE TITLE
BAC-105 ⁃ Add tests for all supported k8s versions to CI

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#530]
Currently we only test the default supported version. Add tests to the Jenkinsfile for running the tests against all k2 supported versions.

Only for k8s on master

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

going to do some config re-writing for this.  probably extend the existing script in build-scripts

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

things to re-write in the config:

  * kubernetes stanza (either version or re-write which one is being set to kubeVersion)
  * etcd version locations 
    * nodePool
    * apiServer config

Need to add version specific kraken directories for 17 & 18

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

https://github.com/samsung-cnct/kraken-lib/pull/1051  -  because jira - github integration isn't on yet.

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

this is complete from my point of view.  Waiting on review and PR merge.

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

PR is merged. Ready for product review.

Incidentally, this lays a reasonable framework for testing upgrades.  make it part of the minus-two and minus-one jobs to upgrade to minus-one and default k8s, respectively
