### ISSUE TITLE
Change default config to have a pinned version of CoreOS

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#547]
Currently we can have an accidental destruction of a running etcd cluster without a user's direct action because we are defaulting the CoreOS version to 'latest'.  The value 'latest' gets passed to terraform and terraform will rebuild any etcd nodes that have had their resolved CoreOS version changed.  When terraform updates CoreOS it destroys the node and recreates it.

If we want to move to a pinned version of CoreOS we would need to add 'checking for a new version of CoreOS' to the weekly version check ticket.  Its small but its another thing to check.

**Comment by coffeepac** [comment]
@davidewatson @guineveresaenger as promised, this issue is for discussing a even faster change to prevent etcd screwups.  Its probably best long term to do both this and #441.

**Comment by joejulian** [comment]
When we're distro agnostic, this is going to cause way too much work. A better solution might be to find a way to only choose latest if tfstate doesn't already exist, otherwise pick the version that's in the current state.

**Comment by davidewatson** [comment]
In view of https://github.com/samsung-cnct/k2/pull/566, should this be closed?

**Comment by coffeepac** [comment]
I think this should have its title changed but left open to continue the discussion.  @joejulian is right, we can't afford to be checking any and every distro for the latest pinned version.  

Answer is probably to clean up the TF module that pulls the version to have that field changing not trigger a rebuild.

**Comment by coffeepac** [comment]
this was done, title never chagned.
