### ISSUE TITLE
Fail earlier if gke cluster fails to deploy.

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#548]
GKE may fail with `Insufficient regional quota to satisfy`, for instance, at `Deploy cluster` but k2 will happily continue on ignoring the error and will fail some time later.

See if there's a reasonable way to fail earlier.

**Comment by coffeepac** [comment]
GKE is run in a parallel path from the AWS stuff.  The process would need to have a way to communicate a fail/abort signal across pipelines.

**Comment by joejulian** [comment]
I'm not talking about Jenkins. The ansible process continues after the Deploy fails.

**Comment by coffeepac** [comment]
oh, that's odd.  thanks for clarifying.
