### ISSUE TITLE
ec2_elb_facts sometimes fails fatally

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#563]
```
FAILED - RETRYING: Wait for ELBs to be deleted (109 retries left).
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: </ErrorResponse>
fatal: [localhost]: FAILED! => {"attempts": 13, "changed": false, "failed": true, "msg": "LoadBalancerNotFound: Cannot find Load Balancer ad7dc468e56cc11e7a4ac02570a8bbd5"}
```

This is an upstream bug which can be followed at:

https://github.com/ansible/ansible/issues/25982

**Comment by DStorck** [comment]
can we quick fix this for now with a `failed_when:` clause so it won't freak?

**Comment by joejulian** [comment]
I don't think so. A fatal error is fatal. I don't think there's any workaround for that.

If you can get a failure with a full stack trace (`-vvv`) and add that to the upstream bug, that would help.
