### ISSUE TITLE
allow external IP address to be configurable

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#575]
Not all users will want to expose every node in the cluster to the outside world.  We should support having a private-ip only configuration.  When this per-cluster flag is set we should also alter the ssh config generation step to use the private ip.  At that point its up to the user to ensure they have a valid route to the node.

**Comment by alejandroEsc** [comment]
@coffeepac would this also require the creation of a bastion?

**Comment by coffeepac** [comment]
not necessarily.  it might be a nice option, but especially in a BYO-vpc environment the users can add other nodes and whatnot on their own.  

probably a good idea though, to at least offer creating one.

**Comment by alejandroEsc** [comment]
@coffeepac would like to take on this task and help, I will post some issue here coming from cts repo, but essentially the requirement is this:

VPCs: 
- K2 created VPC: let the subnets created have the `Auto-assign Public IP: ` option to be configurable by user.
- BYO VPC: not much to do here, we should inherit the subnets options here and we should not do anything. 

LC Configurations: 
Let the Launch configuration the ability to override that option, if defined the attribute will override vpc's subnet option, regardless if defined by k2 or consumer. This could self-defeating, but that is a user issue.

what do you think @coffeepac?

**Comment by coffeepac** [comment]
I think the easiest way to do this is add a per-nodePool option of 'external_ip'.  default would be 'true'.  I think doing anything more complicated would take quite a while to sort through the various network redesigns.

**Comment by sostheim** [comment]
Agree, default behavior should not change.  I would be useful, if it doesn't add to much undue complexity to the solution, to allow the BYO VPC case to support three modes [inherit, force override true, force override false].

This allows for the case when an existing VPC has an value that is inconsistent with the desired setting for the cluster, but the use of the VPC is necessary.  Especially likely in the VPC VGW case.

**Comment by coffeepac** [comment]
linked to samsung-cnct/cts-k8s-2017#37

**Comment by coffeepac** [comment]
waiting for upstream Terraform

**Comment by alejandroEsc** [comment]
Changes made upstream, release updates will contain the changes, I would call this ticket closed @coffeepac

**Comment by coffeepac** [comment]
this issue should be fully resolved when kraken is using terraform 0.10

**Comment by alejandroEsc** [comment]
@coffeepac fair, im guessing we are waiting for which point release to use? Regardless ill be more than happy to verify.

**Comment by coffeepac** [comment]
waiting on time and a reason to move to it.  this is a reason but its a p3 so not on any active list.
