### ISSUE TITLE
scheduler.alpha.kubernetes.io/tolerations has been deprecated

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/kraken-lib#580]
Taints and tolerations have moved from annotations to API fields. We should remove all references to scheduler.alpha.kubernetes.io/tolerations because they are being ignored, and if we still want those tolerations, put it in the appropriate place.  

 PR that changed it : https://github.com/kubernetes/kubernetes/pull/38957

**Comment by coffeepac** [comment]
are we using this annotation anywhere at the moment?

**Comment by DStorck** [comment]
a few places, ex https://github.com/samsung-cnct/k2/blob/a9cf464528959aafb806a9bf70bcecd837adb351/ansible/roles/kraken.fabric/kraken.fabric.weave/templates/weave.yaml.part.jinja2

**Comment by coffeepac** [comment]
this work was completed as part of the 1.8 support process
