### ISSUE TITLE
Merge documentation related directories

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#591]
We currently have:
* /Documentation
* /docs
* /sphinx

Could we arrange these all under one single documentation root directory please? The root's starting to get rather messy.

**Comment by davidewatson** [comment]
/docs and /sphinx are needed. They are essentially the documentation source and build directories. /Documentation will go away once the few tidbits inside are migrated to the new documentation system.

For reference, there are a number of documentation tickets (e.g. #235 and 436). At some point, they should be consolidated, if they aren't fixed before another ticket is opened.

**Comment by joejulian** [comment]
But could they be moved out of root?

**Comment by coffeepac** [comment]
these may be going into their own directory in the next month, lets worry about it then.
