### ISSUE TITLE
consolidate build related directories

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#593]
We have several build related things in the root:

- Makefile
- sphinx
- docker
- build-scripts
- Jenkinsfile

Could we consolidate these under one root directory (`/build` perhaps)?

Yes... I do realize I listed sphinx under the documentation consolidation issue #591 but it's kind-of both. Pick one.

**Comment by coffeepac** [comment]
sphinx may leave entirely and the rest of the build stuff is under active and heavy development.  clean it up when its done.
