### ISSUE TITLE
do we need to specify a kubernetes version for GKE

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#617]
When GKE creates a cluster, GKE will always create the cluster at its default version no matter what you tell Deployment Manager (google product).  GKE will then perform a rolling update of all nodes so they match the target version.  This takes ~45 minutes for default clusters.

We are currently checking the status of this weekly so the K2 default version lines up with the GKE default version.  If its possible, we would prefer to not do this.  It has been suggested that we can specify no Kubernetes version and GKE will give us the (fast) default version.  If so, we should do that for GKE.

**Comment by joejulian** [comment]
The default gke version can be retrieved from the api.

```
$ gcloud container get-server-config --zone=us-west1-a --format json
Fetching server config for us-west1-a
{
  "defaultClusterVersion": "1.6.7",
  "defaultImageType": "COS",
  "validImageTypes": [
    "CONTAINER_VM",
    "COS",
    "UBUNTU"
  ],
  "validMasterVersions": [
    "1.7.2",
    "1.6.7"
  ],
  "validNodeVersions": [
    "1.7.2",
    "1.7.1",
    "1.7.0",
    "1.6.7",
    "1.6.6",
    "1.6.4",
    "1.5.7",
    "1.4.9"
  ]
}
```
