### ISSUE TITLE
update README to include reasons for helm registry over repo

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#629]
a helm repo is the expected case and we're walking away from that to use registry.  why have we made this choice?  what are the pros/cons?  

this should be included in the K2 repo in a useful place, either the main README or as a link from the main README.

**Comment by DStorck** [comment]
Two comments to consider adding to docs:
- https://github.com/samsung-cnct/k2/pull/613#issuecomment-315154631
- https://github.com/samsung-cnct/k2/pull/613#issuecomment-315178440

**Comment by coffeepac** [comment]
don't forget to update the schema blurb as well

**Comment by guineveresaenger** [comment]
What is meant by "schema blurb"? There is a README in the schemas folder but it doesn't mention anything about app registry.

**Comment by guineveresaenger** [comment]
PR: #880

**Comment by guineveresaenger** [comment]
PR's been merged. Self-closing this.
