### ISSUE TITLE
Add k2 config to Kube-Bench

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/kraken-lib#647]
The Kubernetes Bench for Security is a Go application that checks whether Kubernetes is deployed securely by running the checks documented in the CIS Kubernetes 1.6 Benchmark v1.0.0.

https://github.com/aquasecurity/kube-bench

In the README 'Configuration' section, you can see they offer unique testing environments depending what product you used to spin up your cluster, currently KubeADM and KOPS are offered, I suggest we contribute the specs for K2.

**Comment by countspongebob** [comment]
Note that the CIS benchmark was just updated.

![screen shot 2017-10-11 at 8 31 20 am](https://user-images.githubusercontent.com/4932280/31450670-dda863a2-ae5e-11e7-9bd4-e06bc1e850cc.png)
