### ISSUE TITLE
Add check to see if chart was actually installed.

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#651]
Helm fails to return an error code when it times out connecting to tiller and fails to install the chart.

Note the result code is 0. The chart was not installed.

```
    "rc": 0, 
    "start": "2017-07-21 16:10:52.460977", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "E0721 16:11:04.722688   13271 portforward.go:212] Unable to create listener: Error listen tcp6 [::1]:34107: bind: cannot assign requested address\nError: context deadline exceeded", 
    "stdout_lines": [
        "E0721 16:11:04.722688   13271 portforward.go:212] Unable to create listener: Error listen tcp6 [::1]:34107: bind: cannot assign requested address", 
        "Error: context deadline exceeded"
    ]
```

**Comment by mikeln** [comment]
A rudimentary test directly from my mac to a non-existent tiller does return a error code of 1.
```
mikeln-bender:k2 Mikel_Nelson$ helm ls
Error: Get https://35.188.36.218/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 35.188.36.218:443: i/o timeout
mikeln-bender:k2 Mikel_Nelson$ echo $?
1
```

ok, wait, not the same error.

**Comment by davidewatson** [comment]
Can you assist with this?

**Comment by joejulian** [comment]
This should be an upstream bug. If helm errors when installing a chart, the result code should be non-zero.

**Comment by mattfarina** [comment]
Can y'all give me a little more context so that I can reproduce? What commands on what chart was run to produce something that returned a `0` exit code but an error. I've tried several combinations and have not been able to reproduce this situation.
