### ISSUE TITLE
Support Optional VPC Peering for Cluster VPC

### ISSUE THREAD

**Issue by sostheim** [samsung-cnct/kraken-lib#663]
As a Cluster Operator on AWS Cloud Provider infrastructure, I want to be able to have k2 support, as an option, peering with an existing VPC.

The primary use case for this is to be able to launch Kubernetes cluster that can connect to an existing VPC cluster that can facilitate any number of functions including, but not limited to, corporate network access via VPN to Customer Gateway access, existing database infrastructure, existing monitoring and log collection infrastructure.

**Comment by sostheim** [comment]
I think it would be a valid option to be able to peer the VPC post cluster creation.  Maybe as an option to `update`.  The obvious benefit to `update` is that it can be applied to an existing cluster, rather than spinning the cluster again or re-upping it.  

If would be nice to have the option to configure at either cluster `up` or via `update`, but I would by happy to have either option as a first pass at this.

**Comment by coffeepac** [comment]
what would it look like to add this type of functionality for GKE as well.
