### ISSUE TITLE
patch ssh_config generation for private ips

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#674]
patch the ssh_config generation process to look for public ips OR private_ips if only private ips are available.  and use a bastion host if it is available

This will let us back out #672

**Comment by davidewatson** [comment]
+1

**Comment by davidewatson** [comment]
Someone mentioned that there was a ticket for using static IP discovery for etcd servers. I can't find it, but I'll note here, even with local addresses in our ssh_config, they will change over time as nodes fail, or nodes or added. Therefore, I think the gist of this ticket is to give us a way to ssh into problem nodes for PD purposes. I am skeptical about whether local DNS names are the way forward for reliably determining etcd health.

**Comment by alejandroEsc** [comment]
@coffeepac lets chat about how this is related to bastion nodes and my solution to this problem, it may just close this ticket as is.

**Comment by coffeepac** [comment]
the stated goal of this issue is to unwind #672 which we still need to do.  my assumption when writing this issue was that the node kraken was being run from would always have access to the etcd nodes via ssh either directly or over a bastion node.  we have discussed at length how that may not be possible.  

I suppose this issue should either be closed with a new issue or re-written to say, 'ensure that kraken always waits for etcd cluster to come up if possible, ie if a config has either public ips or a bastion node' and go from there.

I'm leaning towards a new issue that links back to this one so we can preserve some history on this.  whenever we get to this we're going to want to have as much context as possible.  its been a bit of a road.
