### ISSUE TITLE
ansible ec2_remote facts  gathering needs security_token set when using temporary credentials

### ISSUE THREAD

**Issue by MrBouncy** [samsung-cnct/kraken-lib#678]
when using STS temporary credentials from a profile, `kraken.ssh.aws` tasks will fail to use the ec2_remote_facts plugin unless the environment carries the AWS_SECURITY_TOKEN or EC2_SECURITY_TOKEN variable

duplicating the logic for access_key_id to lift out the `aws_session_token` field from the credentials cache profile and then specifying the `security_token` key allows the plugin to work without constant environment munging

PR to follow shortly

**Comment by MrBouncy** [comment]
#679 has the fixes that got my environment working..

**Comment by coffeepac** [comment]
the linked PR completed this.
