### ISSUE TITLE
taints should be able to be applied to nodepools

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#680]
Currently, taints can only be applied to node definitions. These should be able to be applied to nodepools.

**Comment by DStorck** [comment]
@joejulian Should this be in addition to the ability to add them per nodeConfig, or is per nodePool just a better way to handle this ?

**Comment by joejulian** [comment]
It probably should be in addition. I don't think that would be difficult to do. Adding them to the nodePools is likely to be used for organizational needs where nodeConfig is more likely for "physical" constraints.

**Comment by DStorck** [comment]
work is done here: https://github.com/samsung-cnct/k2/pull/758

**Comment by DStorck** [comment]
Update - working towards moving taints and labels to live together in a nodePool config called podScheduling.

**Comment by DStorck** [comment]
fixed all requested changes on PR
