### ISSUE TITLE
Do We Want to Enable NodeAuthorization?

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/kraken-lib#700]
New in 1.7   NodeAuthorization... should we use it?

https://kubernetes.io/docs/admin/authorization/node/

**Comment by alejandroEsc** [comment]
Any idea of what the suggested use-cases? Sounds a bit risky security wise and not really something i have considered as a feature k8s was missing...

**Comment by coffeepac** [comment]
find me for 1.8 work

**Comment by davidewatson** [comment]
I think we will we want to enable it at some point. Otherwise, isn't a single compromised kubelet is equivalent to a compromised cluster?

**Comment by davidewatson** [comment]
Some more background from Slack: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/bulk_watch.md

**Comment by coffeepac** [comment]
completed as part of 1.8 support.
