### ISSUE TITLE
code cleanup:  services files

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#716]
the files task/manage-services.yaml and tasks/run-services in ansible/roles/kraken.services are very similar and should be refactored to share code/stanzas between them.  presently, this is a piece of tech debt waiting to cause us a bunch of pain.

**Comment by joejulian** [comment]
Most of run-services could probably be replaced with the helm commands from manage-services.

See #712

**Comment by joejulian** [comment]
Mostly the difference is in 
https://github.com/samsung-cnct/k2/blob/master/ansible/roles/kraken.services/tasks/manage-services.yaml#L15-L34
and 
https://github.com/samsung-cnct/k2/blob/master/ansible/roles/kraken.services/tasks/manage-services.yaml#L84-L113
