### ISSUE TITLE
Analysis of changes required for kubeadm adoption

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#726]
The community is moving to using kubeadm for all kubernetes level cluster provisioning, ie:  building control planes, adding/removing worker nodes, configuring the required SSL, etc.  We have publically committed to joining this group over the next few quarters.

An initial pass of the kubeadm docs show a few show stoppers (listed below) and some other possible issues, we need to go through and find exactly what we need to change to build an HA kraken cluster with kubeadm.

reference material:
- https://github.com/kubernetes/kubeadm/blob/master/docs/design/design.md 
- https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#limitations
- https://kubernetes.io/docs/admin/kubeadm/

**Comment by coffeepac** [comment]
First level show stoppers:
Kubeadm does not support running the kubelet as a container, which we do.  
Kubeadm uses a single node self-hosted etcd cluster which we recommend against.

**Comment by coffeepac** [comment]
Areas of concern:
- missing cloud provider information?  docs suggest this but maybe this was a 1.4 limitation that has been cleared
- exact method for installing network fabric
- applying taints to nodepools as part of kubelet manifest
- re-arranging the order of how we do things to fit into the kubeadm phases (they install DNS before network, etc)

**Comment by mikeln** [comment]
What is our strategy here for the missing items?  Will we just use kubeadm where we can and work around it in other places.  Or will we attempt to push the community development of kubeadm to do what we need?
