### ISSUE TITLE
helm_override behavior change

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#764]
we are dropping formal support for allowing a user to specify their application helm charts in the kraken configuration file, as such we no longer need to have a discussion with the user during `cluster up` or `cluster update` about explicit helm version support for a specific version of kubernetes.  

we should update the helm_overide code path to:
- still always use the correct version of helm for a given version of kubernetes
- if the selected version of kubernetes does not have a matching helm version, use the newest version of helm

This means we will take ownership for ensuring system level helm charts are compatible with helm/kubernetes version mismatches in CI.

**Comment by guineveresaenger** [comment]
This was addressed here: https://github.com/samsung-cnct/kraken-lib/pull/968
and was added to the config v2 issue as per comment [here](https://github.com/samsung-cnct/kraken-lib/issues/801#issuecomment-346105588).
