### ISSUE TITLE
Use etcdctl v3

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/kraken-lib#786]
The version of etcdctl on our nodes is the default CoreOS version...which is v2.  
However, we run etcd v3 for our cluster.

We frequently ssh to an etcd node and run etcdctl.  This results in etcdctl v2 querying etcd v3.

Some etcdctl items needed for etcd v3 are not there. (e.g. backup/snapshot is completely different).

We need to make sure we run the etcdctl binary that comes with the etcd release we are running.  This means we should be running etcdctl via a container that has the current etcd version.

e.g.:  
```
sudo rkt run --net=host --volume ssl,kind=host,source=/etc/etcd/ssl,readOnly=true --mount volume=ssl,target=/etc/etcd/ssl --set-env=ETCDCTL_API=3 coreos.com/etcd:v3.2.5 --exec etcdctl -- --cacert=/etc/etcd/ssl/client-ca.pem --cert=/etc/etcd/ssl/client.pem --key=/etc/etcd/ssl/client-key.pem --endpoints=https://127.0.0.1:2381  member list
```
(this isn't quite correct, but you get the idea).

**Comment by mikeln** [comment]
I don't think this has any relative impact yet.  However, for backup/recovery this has to be fixed.

**Comment by davidewatson** [comment]
If you run etcdctl from k2-tools, the [Dockerfile](https://github.com/samsung-cnct/k2-tools/blob/master/Dockerfile#L17) already sets this for you. Interestingly though, if you read the etcdctl source, some options are still implemented using the etcd2 protocol. It is not clear to me which features of etcd3 we require from the command line. Backup and recovery make sense.

**Comment by mikeln** [comment]
Yes, but we ssh to the nodes to test status...i.e. we don't run the k2-tools version.

Also you have to set ETCDCTL_API=3 for v3 etcdctl to run as v3...
Note: v3 has different arg names and commands.

**Comment by alejandroEsc** [comment]
```ETCDCTL_API=3 ./etcdctl
NAME:
	etcdctl - A simple command line client for etcd3.

USAGE:
	etcdctl

VERSION:
	3.2.6

API VERSION:
	3.2


COMMANDS:
	get			Gets the key or a range of keys
	put			Puts the given key into the store
	del			Removes the specified key or range of keys [key, range_end)
	txn			Txn processes all the requests in one transaction
	compaction		Compacts the event history in etcd
	alarm disarm		Disarms all alarms
	alarm list		Lists all alarms
	defrag			Defragments the storage of the etcd members with given endpoints
	endpoint health		Checks the healthiness of endpoints specified in `--endpoints` flag
	endpoint status		Prints out the status of endpoints specified in `--endpoints` flag
	watch			Watches events stream on keys or prefixes
	version			Prints the version of etcdctl
	lease grant		Creates leases
	lease revoke		Revokes leases
	lease timetolive	Get lease information
	lease keep-alive	Keeps leases alive (renew)
	member add		Adds a member into the cluster
	member remove		Removes a member from the cluster
	member update		Updates a member in the cluster
	member list		Lists all members in the cluster
	snapshot save		Stores an etcd node backend snapshot to a given file
	snapshot restore	Restores an etcd member snapshot to an etcd directory
	snapshot status		Gets backend snapshot status of a given file
	make-mirror		Makes a mirror at the destination etcd cluster
	migrate			Migrates keys in a v2 store to a mvcc store
	lock			Acquires a named lock
	elect			Observes and participates in leader election
	auth enable		Enables authentication
	auth disable		Disables authentication
	user add		Adds a new user
	user delete		Deletes a user
	user get		Gets detailed information of a user
	user list		Lists all users
	user passwd		Changes password of user
	user grant-role		Grants a role to a user
	user revoke-role	Revokes a role from a user
	role add		Adds a new role
	role delete		Deletes a role
	role get		Gets detailed information of a role
	role list		Lists all roles
	role grant-permission	Grants a key to a role
	role revoke-permission	Revokes a key from a role
	check perf		Check the performance of the etcd cluster
	help			Help about any command

OPTIONS:
      --cacert=""				verify certificates of TLS-enabled secure servers using this CA bundle
      --cert=""					identify secure client using this TLS certificate file
      --command-timeout=5s			timeout for short running command (excluding dial timeout)
      --debug[=false]				enable client-side debug logging
      --dial-timeout=2s				dial timeout for client connections
      --endpoints=[127.0.0.1:2379]		gRPC endpoints
  -h, --help[=false]				help for etcdctl
      --hex[=false]				print byte strings as hex encoded strings
      --insecure-skip-tls-verify[=false]	skip server certificate verification
      --insecure-transport[=true]		disable transport security for client connections
      --key=""					identify secure client using this TLS key file
      --user=""					username[:password] for authentication (prompt if password is not supplied)
  -w, --write-out="simple"			set the output format (fields, json, protobuf, simple, table)```

vs

```
./etcdctl
NAME:
   etcdctl - A simple command line client for etcd.

WARNING:
   Environment variable ETCDCTL_API is not set; defaults to etcdctl v2.
   Set environment variable ETCDCTL_API=3 to use v3 API or ETCDCTL_API=2 to use v2 API.

USAGE:
   etcdctl [global options] command [command options] [arguments...]

VERSION:
   3.2.6

COMMANDS:
     backup          backup an etcd directory
     cluster-health  check the health of the etcd cluster
     mk              make a new key with a given value
     mkdir           make a new directory
     rm              remove a key or a directory
     rmdir           removes the key if it is an empty directory or a key-value pair
     get             retrieve the value of a key
     ls              retrieve a directory
     set             set the value of a key
     setdir          create a new directory or update an existing directory TTL
     update          update an existing key with a given value
     updatedir       update an existing directory
     watch           watch a key for changes
     exec-watch      watch a key for changes and exec an executable
     member          member add, remove and list subcommands
     user            user add, grant and revoke subcommands
     role            role add, grant and revoke subcommands
     auth            overall auth controls
     help, h         Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug                          output cURL commands which can be used to reproduce the request
   --no-sync                        don't synchronize cluster information before sending request
   --output simple, -o simple       output response in the given format (simple, `extended` or `json`) (default: "simple")
   --discovery-srv value, -D value  domain name to query for SRV records describing cluster endpoints
   --insecure-discovery             accept insecure SRV records describing cluster endpoints
   --peers value, -C value          DEPRECATED - "--endpoints" should be used instead
   --endpoint value                 DEPRECATED - "--endpoints" should be used instead
   --endpoints value                a comma-delimited list of machine addresses in the cluster (default: "http://127.0.0.1:2379,http://127.0.0.1:4001")
   --cert-file value                identify HTTPS client using this SSL certificate file
   --key-file value                 identify HTTPS client using this SSL key file
   --ca-file value                  verify certificates of HTTPS-enabled servers using this CA bundle
   --username value, -u value       provide username[:password] and prompt if password is not supplied.
   --timeout value                  connection timeout per request (default: 2s)
   --total-timeout value            timeout for the command execution (except watch) (default: 5s)
   --help, -h                       show help
   --version, -v                    print the version
```

**Comment by alejandroEsc** [comment]
ugh, the flags are different, so if i wanted to use cluster-health it would require a change of environment variable and flags, sigh.

**Comment by davidewatson** [comment]
I haven't dug into potential incompatibilities, but for as far as `cluster-health` goes, I don't think it's a problem.

```
core@ip-10-0-175-130 ~ $ etcdctl --version
etcdctl version 2.3.7
core@ip-10-0-175-130 ~ $ ETCDCTL_API=2 etcdctl --endpoint https://127.0.0.1:2379 --ca-file=/etc/etcd/ssl/peer-ca.pem --cert-file=/etc/etcd/ssl/peer.pem --key-file=/etc/etcd/ssl/peer-key.pem cluster-health
member 133ef08f66f8d5fc is healthy: got healthy result from https://10.0.42.238:2379
member a35104fa78e6be0a is healthy: got healthy result from https://10.0.219.80:2379
member b185e28292711e2e is healthy: got healthy result from https://10.0.121.19:2379
member cee4cb6c9c90611e is healthy: got healthy result from https://10.0.175.130:2379
member e478ebcd8a7b53fc is healthy: got healthy result from https://10.0.67.86:2379
cluster is healthy
core@ip-10-0-175-130 ~ $ ETCDCTL_API=3 etcdctl --endpoint https://127.0.0.1:2379 --ca-file=/etc/etcd/ssl/peer-ca.pem --cert-file=/etc/etcd/ssl/peer.pem --key-file=/etc/etcd/ssl/peer-key.pem cluster-health
member 133ef08f66f8d5fc is healthy: got healthy result from https://10.0.42.238:2379
member a35104fa78e6be0a is healthy: got healthy result from https://10.0.219.80:2379
member b185e28292711e2e is healthy: got healthy result from https://10.0.121.19:2379
member cee4cb6c9c90611e is healthy: got healthy result from https://10.0.175.130:2379
member e478ebcd8a7b53fc is healthy: got healthy result from https://10.0.67.86:2379
cluster is healthy
core@ip-10-0-175-130 ~ $ 
```

**Comment by alejandroEsc** [comment]
@davidewatson yes that works, but look at the flags for v3, i cant just change environment variable and run a command.

**Comment by alejandroEsc** [comment]
Work on  kraken (cli) will allow for the right version of etcdctl and effectively fix this issue. I suggest we close this ticket @mikeln , is this ok?

**Comment by mikeln** [comment]
yes, when the PR for this is merged.

**Comment by davidewatson** [comment]
https://github.com/samsung-cnct/kraken/pull/176
