### ISSUE TITLE
gke provider needs to use cluster directory for cluster credentials 

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/kraken-lib#787]
the gke provider uses gcloud to create the cluster. gcloud defaults to using the user's default kubectl config file which is located at ~/.kube/config .  We should be saving this file to ${OUTPUT_DIR}/<cluster_name>/admin.kubeconfig.

**Comment by oneilcin** [comment]
@DStorck I brought a GKE cluster up (kraken k8s version 1.7.6), and made sure I could use kubectl with the $HOME/cluster_name/admin.kubeconfig.  This worked.   Can you please explain what needs to be tested?  

My commands:
docker run $K2OPTS quay.io/samsung_cnct/k2:latest ./bin/up.sh --config $HOME/.kraken/cindygke.yaml
kubectl --kubeconfig=/Users/cynthiaoneill/.kraken/cindygke/admin.kubeconfig get nodes

**Comment by oneilcin** [comment]
@coffeepac I'm seeing a problem, can you look at the comment above (when you are back, no rush!), and see if there's anything else I need to check?

**Comment by coffeepac** [comment]
this seems to have been resolved at some point.  closing as we can't duplicate it anymore.
