### ISSUE TITLE
create a deprecation warning for helm_override commands

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#801]
As per #764 we are going to be changing our expected helm usage.  We should be removing the user challenge bits from this repo (we need to leave them for the cli as we still have `kraken tool helm` and that will require the user-interaction).

**Comment by guineveresaenger** [comment]
I actually see the PR fixing this issue: https://github.com/samsung-cnct/kraken-lib/issues/764

but there is no deprecation warning in kraken-lib; is there?

@coffeepac can you weigh in on what still needs to be done?

**Comment by guineveresaenger** [comment]
Do we still need an explicit deprecation warning for helm_override commands? Or is the change in the README sufficient?

**Comment by coffeepac** [comment]
this issue was intended to only cover adding a warning that the now-merged PR was going to be happening.  there is some cruft in the config file that we will need to remove but we don't actually have a means for signalling a deprecation warning to the user at run time.  I'll add this to the config v2 issue.

**Comment by coffeepac** [comment]
update the v2alpha config ticket.  closing this.
