### ISSUE TITLE
DNS Updates for 1.7.x/1.8.x

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/kraken-lib#803]
Eval DNS updates for 1.7.x
one extra source, apart from the usual kubernetes: https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/deployments/kube-dns.yaml

**Comment by mikeln** [comment]
now for 1.8..  compare with kuberntes/cluster/addons/dns  version which we use/base our ansible templates on.

**Comment by coffeepac** [comment]
This seems to have been completed as part of the 1.8 support process.  I can find no difference between the linked yaml, what kraken ships and what is present in the dns addons directory.

if I'm wrong, please re-open with what I missed.
