### ISSUE TITLE
Etcd nodes need fluent-bit for logging

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/kraken-lib#825]
Since etcd is not hosted by k8s, we will not be able to capture its logs using the [fluent-bit dameonset](https://github.com/samsung-cnct/k2-logging-fluent-bit-daemonset). One solution would be to render systemd units to deploy fluent-bit on etcd nodes.

**Comment by davidewatson** [comment]
Closing in favor of https://github.com/samsung-cnct/kraken-lib/issues/825

**Comment by coffeepac** [comment]
This issue was closed in favor of itself.  I am re-opening so we don't lose this as an issue.

**Comment by davidewatson** [comment]
So I did some preliminary work on this.

Using a simple `kraken-fluent-bit.service` unit file:

```
[Unit]
Description=Kraken fluent-bit for monitoring non-kubernetes nodes
After=kraken-networking.service
Requires=kraken-networking.service
[Service]
EnvironmentFile=/etc/network-environment
TimeoutStartSec=0
RestartSec=15
Restart=always
KillMode=none
ExecStart=/usr/bin/rkt run --net=host \
 --stage1-path=/usr/lib/rkt/stage1-images/stage1-fly.aci \
 --insecure-options=image \
 --inherit-env=true \
 --volume resolv-conf,kind=host,source=/etc/resolv.conf \
 --mount volume=resolv-conf,target=/etc/resolv.conf \
 quay.io/samsung_cnct/fluent-bit-container:latest
ExecStopPost=/usr/bin/rkt gc --mark-only
```

We get these errors:

```
Nov 05 20:38:06 ip-10-0-100-240.ec2.internal rkt[1814]: [2017/11/05 20:38:06] [ info] [filter_kube] https=1 host=kubernetes.default.svc port=443
Nov 05 20:38:06 ip-10-0-100-240.ec2.internal rkt[1814]: [2017/11/05 20:38:06] [error] [filter_kube] cannot open /var/run/secrets/kubernetes.io/serviceaccount/namespace
Nov 05 20:38:06 ip-10-0-100-240.ec2.internal rkt[1814]: [2017/11/05 20:38:06] [ info] [filter_kube] not running in a POD
Nov 05 20:38:06 ip-10-0-100-240.ec2.internal rkt[1814]: [2017/11/05 20:38:06] [error] [TLS] Invalid CA file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt | PK - Read/
Nov 05 20:38:06 ip-10-0-100-240.ec2.internal rkt[1814]: [2017/11/05 20:38:06] [ info] [filter_kube] testing connectivity with API server...
Nov 05 20:38:06 ip-10-0-100-240.ec2.internal rkt[1814]: [2017/11/05 20:38:06] [error] [filter_kube] could not get meta for POD (null)
```

There (at least) two ways to fix this

1) Modify the default `fluent-bit.conf` in https://github.com/samsung-cnct/container-fluent-bit to not assume a kubernetes cluster and then use ConfigMaps in https://github.com/samsung-cnct/chart-fluent-bit to configure the kubernetes nodes. One downside of this approach is that the container would not be useful for kubernetes nodes without a ConfigMap. I am not sure if this is really a downside, since we should be using ConfigMaps anyway.

2) Pass a non-kubernetes `fluent-bit.conf` into the systemd invocation of fluent-bit. One downside of this approach is that we would have to pass the config through our already crowded cloud-init.

I lean towards the former solution.

<EOM>

**Comment by coffeepac** [comment]
huge +1 to the first option.  we should be using configmaps for everything.

**Comment by joejulian** [comment]
As an aside... cloud-config user_data is no longer all that crowded.
