### ISSUE TITLE
Add Restart to kraken-etcd unit files

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#830]
If the kraken-etcd service fails to start for reasons like an image download timeout, that etcd node will never recover from that. Even if etcd crashes, we should make some attempt at restarting that service. 

Add Retries to the service file.

**Comment by alejandroEsc** [comment]
Should we? I ask because i rather the cluster fail to try to figure out what the issue was and potential deal with state. Let alone have a process restart that i want killed.

**Comment by joejulian** [comment]
Yes. Yes we do. If you want a process killed, use systemctl.

**Comment by alejandroEsc** [comment]
Could you write out your specific situation, just to understand  a bit more.

**Comment by davidewatson** [comment]
I think we need to do for the etcd units the same thing @joejulian did here: https://github.com/samsung-cnct/kraken-lib/blob/69e66d834d297ac3739e4dade48c719afc6df7f0/ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/units.kubelet.part.jinja2#L7-L8 and here https://github.com/samsung-cnct/kraken-lib/blob/69e66d834d297ac3739e4dade48c719afc6df7f0/ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/units.kubelet.part.jinja2#L15
