### ISSUE TITLE
./update.sh --addnodepools causes helm version downgrade

### ISSUE THREAD

**Issue by sostheim** [samsung-cnct/kraken-lib#837]
On an long running cluster, the act of adding a node pool to the cluster via the update script, causes the helm version to be downgraded.

Specifically, from within a running cluster, using the kraken-lib (k2:latest) image base on the `krak8s` Pod, running the command:
```
./bin/update.sh --config /root/.kraken/config.yaml --output /root/.kraken/ --addnodepools nexusNodes
```
Causes the following behavior:
```
helm registry install quay.io/samsung_cnct/mongodb-replicaset --namespace test-ns --name test-mongodb --values /tmp/prefix868881021 --version 1.2.0-0
usage: appr [-h]
            {pull,run-server,show,inspect,list,delete-package,helm,version,logout,deploy,plugins,push,login,config,channel,jsonnet}
            ...
appr: error: 
message: 'Error: incompatible versions client[v2.6.1] server[v2.5.1]
```

**Comment by sostheim** [comment]
On the krak8s Pod node:
```
# helm version
Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
```
Then proceeding with a helm upgrade:
```
/ # helm init --upgrade
Creating /etc/helm/repository 
Creating /etc/helm/repository/cache 
Creating /etc/helm/repository/local 
Creating /etc/helm/starters 
Creating /etc/helm/cache/archive 
Creating /etc/helm/repository/repositories.yaml 
$HELM_HOME has been configured at /etc/helm.

Tiller (the Helm server-side component) has been upgraded to the current version.
Happy Helming!
/ # helm version
Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
```
After which, the helm install shown in the issue description above succeeds.

**Comment by sostheim** [comment]
This appears to be related to the failures described in https://github.com/samsung-cnct/krak8s/issues/10

**Comment by alejandroEsc** [comment]
This sounds like what i would expect that kraken is doing: On update, when it runs the config changes, it sticks to the helm versioned defined in the config. When you do a manual upgrade it does upgrade the server version, but that isnt part of the original config file and so reverts. Is the version on the config file the previous version?

**Comment by sostheim** [comment]
Note: tried to affect / control this behavior by changing the value in `config.yaml` of `overrideHelm` without any effect.
```
git diff config.yaml
       kubeAuth: *colonybeadKubeAuth
        helmConfig: *colonybeadHelm
        dnsConfig: *defaultDns
 -      helmOverride:
 +      helmOverride: true
    readiness:
      type: exact
      value: 0
```

**Comment by sostheim** [comment]
I don't see a version of helm specified in the config.yaml at present.  Where would that value be in the configuration file?

**Comment by alejandroEsc** [comment]
I just looked, and i just noticed the same thing.... this may be part of the problem...

**Comment by sostheim** [comment]
We observed that this also occurs when running `./bin/update.sh --rmnodepools ...`.

**Comment by alejandroEsc** [comment]
my guess, is that the update.yaml file should look like this 
```
  roles:
    - {
        role: '{{ playbook_dir }}/roles/kraken.update/kraken.update.selector',
      }
    - {
        role: 'roles/kraken.services',
        tags: [ 'services', 'all' ]
      }
```

Again this is a guess, but it seems the services roles actually run an update task on helm. My guess is that it should run after the update is complete also. Since it is something done after nodes are up.

**Comment by sostheim** [comment]
We may also need to rethink the logic here (credit @venezia):
https://github.com/samsung-cnct/kraken-lib/blob/master/ansible/roles/kraken.services/tasks/manage-services.yaml#L24-L34
Can this be protected by a flag in the helm configuration root options section to prevent execution when desired?

**Comment by guineveresaenger** [comment]
Rick, what is the k8s version of the node you are adding? And is this an AWS cluster?

**Comment by coffeepac** [comment]
we are currently pinning the version of helm to the minor version of kubernetes installed.  we experienced negative behavior (helm was non-functional) when we did not do this.  

@sostheim is there a reason you aren't using the version of helm installed into `/opt/cnct/kubernetes/v1.6/bin/helm`?  I'm guessing you are using kubernetes v1.6, if not, please sub in your running version of kubernetes.

**Comment by sostheim** [comment]
Kube version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.8", GitCommit:"d74e09bb4e4e7026f45becbed8310665ddcb8514", GitTreeState:"clean", BuildDate:"2017-08-03T18:12:08Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sostheim** [comment]
```
# /opt/cnct/kubernetes/v1.6/bin/helm version
Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
# which helm
/usr/bin/helm
# /usr/bin/helm version
Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
```

**Comment by sostheim** [comment]
@venezia - can you give us the background on the need for being able to 1) run helm 2.6.1 in this cluster, 2) being able to run a version of helm other than the version installed w/ the cluster in a general sense.

**Comment by coffeepac** [comment]
since you are using helm directly you will want to follow the conventions that kraken-lib follows which is to explicitly use the expected version for helm and kubectl.

**Comment by sostheim** [comment]
@coffeepac - so, I generally agree with the pinning of a version of helm with the initial deployment, but what I think is hanging us up here is the need to reinstall helm during a operation on a node pool add/update/remove.  Why would this trigger any change to the installed version of helm?

**Comment by sostheim** [comment]
Let me put it another way, day 0 -> pinned version of helm perfectly sensible, day 54 -> pinned version of helm may not be sensible. 

I get that this is a safeguard for kraken to be able to operate sanely, but for a situation where cluster components are updated, we need to be able to override this behavior.

**Comment by coffeepac** [comment]
kraken-lib on day 54 has the same expectations of the installed components as it did on day 0.  if you change things underneath kraken-lib on it you should expect a bad time.

but I don't think that tiller was upgraded.  I think that you are using the kraken-tools default version of helm instead of the version of helm that is pinned to a specific version of kubernetes.  this is causing kr8kas some confusion.

**Comment by venezia** [comment]
* there's no reason why we can't ask kraken team to give a `--skip-services` statement to add/remove nodes.  One can say one _wants_ to run it, but there's no explicit need to run it
* there's a movement/realization that perhaps they should be always running the latest helm (it would reduce image size if nothing else, and clean up some of the logic in kraken)
* there's a ticket joe filed ( #838 ) to have it such that there is a customer tiller and a kraken/cluster ops tiller
* we could create a tiller for a customer today - in say namespace `krak8s`, have krak8s use that tiller for _its_ helm statements

The first two would obviate our need to do anything with krak8s today.  The last option is feasible too, however it will not allow for migrations of deployments between tillers.

As a kraken user, I'm not happy services is re-run when I ask for more or less nodes.  It has nothing to do with my request - why do work I don't ask you to do?

**Comment by sostheim** [comment]
Testing #839 - 
Before: 
```
# helm version 
Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
```
Running `./bin/update.sh --rmnodepools ...`

After:
```
/ # helm version
Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
```

**Comment by sostheim** [comment]
Added new node pool just now and results are the same, no change to helm version.  An added benefit is that the update command now runs in less than half of the time of the previous run.  Haven't had enough samples yet to quantify this accurately.  Previously the average add would take 5m give or take a little.  The last run took just over 90s.
```
I0921 22:36:22.329985       1 runner.go:420] Queued task delted: type: AddProject, name: nexus, namespace: nexus-core, queueing duration: 1m32.509792649s, running duration 1m32.507908623s
``

**Comment by sostheim** [comment]
Appears to be working as requested.  Will close this ticket and reopen (or create a new ticket) if needed.
