### ISSUE TITLE
Install tiller into a kraken namespace

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#838]
Based on @venezia's [gist](https://gist.github.com/venezia/69e9bd25d79fec9834fe1c5b589d4206) about namespacing tiller and an end-user experience where the user upgraded tiller but kraken downgraded it again as part of a nodePool addition - we should have our own tiller install for kraken use.

This isn't hard. We would just use the `--tiller-namespace` flag. This would require we use helm >= 2.6.0. 

Using a single version of helm is a departure from our current process but there has been an argument put forward that we should be testing and using the latest helm with all versions of kubernetes anyway as client-go is supposed to be backward compatible.

**Comment by alejandroEsc** [comment]
I have a question about that. Why isnt tiller/helm installed like other apps that are defined? Well i suppose the other apps are defined via charts, but still feels like its something about our idea of what k8s should be and so these should be considered... i think?

**Comment by joejulian** [comment]
I'm not sure I'm parsing what you're asking. 

Helm is an application management tool not a long-running k8s service so it only exists as a binary that's called by kraken. 

Tiller _is_ a kubernetes pod, but it's installed by helm and must exactly match the helm version. It would be more work and harder to maintain installing tiller via kubectl considering that restriction.

**Comment by alejandroEsc** [comment]
ahhh ok what i mean is that we select specific versions of helm to run per version of k8s no? how flexible is that? specially when it seems you are changing versions of helm

**Comment by joejulian** [comment]
Currently, yes. We do run specific versions of helm based on the kubernetes version installed. It's completely inflexible as it depends on the helm that's installed in kraken-tools. Part of my suggestion is that we stop doing that and, instead, use a single (latest) version of helm (provided that version passes our CI for all supported versions of kubernetes - a test we don't yet do).

**Comment by joejulian** [comment]
By "boxing in" our helm/tiller into our own namespace, this allows us some safety in choosing what works for kraken. If it passes CI, it can safely ship without worrying that it may not support some feature a customer needs.

Additionally, it solves the helm-lags-behind-k8s concern as we don't have to care if helm supports all the new features and instead only have to care if helm can finish preparing the cluster as defined by kraken and tested in CI.

**Comment by oneilcin** [comment]
I'm trying to understand the desired helm setup, and wether this issue covers doing the whole desired outcome (may need to be broken up?). 
1. Currently kraken-tools Dockerfile installs the version of helm that is fully supported by the desired k8s version. Do we want to change this to always install the latest helm here?
2. Currently kraken-lib looks at an 'helm_override==""' to set the helm binary path with the one installed by kraken-tools Dockerfile. Should we get rid of helm_override?
3. Tiller is installed as part of kraken.services ("helm init") and is used (I think) only for our helmConfig.charts installs. So this would be installed in kube-system namespace since we didn't pass in a --tiller-namespace.
4.  Are you proposing that the user does his own "helm init --namespace whatever"?  (that would be easy :))

**Comment by oneilcin** [comment]
To make it secure (after reading @venezia gist) we probably don't want to install our Tiller into kube-system (note 3).  So this could be installed into our own namespace.

**Comment by DStorck** [comment]
@joejulian @venezia any way either or both of you could take a crack at answering @oneilcin 's questions above?  I am trying to figure out what actions should be associated with this ticket.

**Comment by coffeepac** [comment]
I will take a crack at @oneilcin questions:
1. no.  that should be a separate issue
2. yes but in a different issue. we do want to maintain this for users who end up using `kraken tool helm` to notify them there may be issues
3. as noted, we would need to install this tiller into a kraken controlled namespace (`kraken` probably).  however, it does have a service account, all pods in kubernetes have a service account.  if a service account isn't specified the pod gets the `default` service account.  we should investigate giving tiller a specific service account and then applying RBAC roles to give that account admin controls over the following namespaces:
- kraken
- kube-networking (maybe?)
- kube-system (maybe?)
- any other namespaces that are referenced in the helmConfigs section (required so that tiller can create pods there)
4. yes!
5. yes!

**Comment by joejulian** [comment]
4. Yes, but we shouldn't _expect_ them to. If they install in default, that should interfere with or in any other way affect kraken's ability to do its job.

**Comment by coffeepac** [comment]
@joejulian i think you are missing a not in your comment?  As in, the user installing tiller into the default namespace shouldn't interfere with krakens tiller.  Right?

**Comment by joejulian** [comment]
Oops, right. I even proof read that twice before I hit the button and read the missing "not" each time.

For the sake of accuracy, I meant:

4. Yes, but we shouldn't _expect_ them to. If they install in `default`, that should not interfere with or in any other way affect kraken's ability to do its job.

**Comment by DStorck** [comment]
should i also change the helm command that gets spit out when a cluster goes up? the `To use helm: ` command....   and are we going to change up the `kraken tool helm` command to reflect needing `--tiller-namespace kraken` as well?

**Comment by joejulian** [comment]
I think the point is that we don't want users messing with (upgrading, etc) our tiller. Maybe suggesting they use a namespace is valuable, but not the kraken namespace. I don't expect `kraken tool helm` should operate in the kraken namespace.

**Comment by venezia** [comment]
namespaces are cheap though.  So its not like you're causing a huge issue if you created a `kraken` or `kraken-tiller` namespace.  There may even be some side benefits of doing such (namespace generally are easily isolated from each other, so you could isolate an administration tool into its own little world)

**Comment by DStorck** [comment]
I guess my comment about the `to use helm` helm command is that if we use dockerdev or `docker run....` to bring up a cluster, the user (us) won't be able to even run a `helm list`.  But yes i agree that kraken tool should not by default be in the kraken namespace.

**Comment by DStorck** [comment]
work is here: https://github.com/samsung-cnct/kraken-lib/pull/919
To Review: 
check out the PR, and I asked a question in my first comment (of the PR) . that i would like feedback on.

**Comment by DStorck** [comment]
PR was merged - but there were no comments about what the `helm` command given at the end of a cluster up should be. Right now someone who doesn't know this PR was merged will be confused if they try to run any helm commands and don't pass `--tiller-namespace kraken`.  So is it better to document this just in kraken-lib , or just change the helm command given to the user, or both?

**Comment by joejulian** [comment]
Since our expectation is that the user should not see that output, I would lean toward changing the output. Maybe make some statement about how this is for manual operations to a kraken managed cluster and not to be used for user applications.

**Comment by DStorck** [comment]
I think at the moment what I don't like is that at cluster creation using... we spit out something like : ```To use helm:
------------

    KUBECONFIG=/root/.kraken/ds-klog/admin.kubeconfig HELM_HOME=/root/.kraken/ds-klog/.helm helm <helm command>```
right now, this will do nothing... and I'm talking about clusters brought up using kraken-lib, which in theory, is us. or a dev...

**Comment by joejulian** [comment]
Right, but it's still _possible_ for a user to see that if they enable verbose output from kraken.

**Comment by DStorck** [comment]
So does it make sense for our default output  ( or kraken-lib docs ) to mention how a user can install their own tiller?

**Comment by joejulian** [comment]
I guess it couldn't hurt to add that to the docs.

**Comment by DStorck** [comment]
made ticket for updating documentation: https://github.com/samsung-cnct/kraken-lib/issues/943

**Comment by coffeepac** [comment]
good to go.
