### ISSUE TITLE
A little typo on README.md

### ISSUE THREAD

**Issue by blackdog0403** [samsung-cnct/kraken-lib#847]
When I excuted a command on README.md below..
```
$docker pull quay.io/samsung_cnct/K2:latest
Error parsing reference: "quay.io/samsung_cnct/K2:latest" is not a valid repository/tag
```

**'K2' -> 'k2'** 

People who love copy & paste will fail at very beginning.

**Comment by davidewatson** [comment]
“People who loves copy & paste will fail at very beginning.”

I think it depends on who the typer is. ;)
