### ISSUE TITLE
Bastion support for non-standard ports needs reworked

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#850]
The current method for setting the bastion ssl port is to create a write_file in cloud_config to update /etc/ssh/sshd_config. Unfortunately, coreos is a read-only operating system and that file cannot be written to.

This needs to be managed differently. Perhaps with a sshd.socket unit.

**Comment by alejandroEsc** [comment]
Interesting. FYI sshd.socket i believe is done already. please check i think thats how port is selected in bastions, or rather thats how i designed it. If not ill have to check what the original possible issues were.

**Comment by coffeepac** [comment]
@joejulian if you are working on this please add to the board.

**Comment by joejulian** [comment]
Closing. I removed the write_file from #861 as the sshd.socket that was also in there satisfies this need.
