### ISSUE TITLE
Please add iops setting support in EBS configuration

### ISSUE THREAD

**Issue by venezia** [samsung-cnct/kraken-lib#853]
in [awsEbsStorageOptions.json](https://github.com/samsung-cnct/kraken-lib/blob/master/schemas/config/v1/awsEbsStorageOptions.json) there is no option for the iops budget if a user picks something like `io1` disk type.  This should be added and bubbled into terraform templates

The net result is a potentially faster etcd service

Thanks

**Comment by coffeepac** [comment]
please also investigate if the same pattern that solves this ticket can be applied to the GKE provider.  or at least ensure we don't block solving the GKE provider.
