### ISSUE TITLE
support kubernetes 1.8

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#856]
Its either GA now or will be in the next 12 hours.  

EDIT:  1.8 is actually a bit stuck.  will get an updated ETA later today/tomorrow.

**Comment by joejulian** [comment]
When looking at the templates: if a template needs changed for 1.8 use (or create if it does not exist) versioned directories (v1.7, v1.6) for the _legacy_ templates to support those older versions. The new default will be the 1.8 version template and it should not go in a v1.8 directory.

Only create templates in the v1.7 or v1.6 sub-directories if the template for 1.8 will not work for those older versions.

v1.5 template directories can be removed as support for that version will be dropped with 1.8 support.

**Comment by mikeln** [comment]
Exactly.  There are some inconsistencies when I created some of that structure.  Namely, the DNS ones are "backwards" to that, and need to be fixed..i.e. The default needs to be whatever is current.

**Comment by guineveresaenger** [comment]
Tracking down the API flag to set. as kubectl could not connect to the server. 
Came across a bizarre error in cluster name in the message for kubectl (was using a different, previous cluster name, but within kraken-lib, so that is confusing).

**Comment by guineveresaenger** [comment]
Set API flag in correct place.
Got kubelet talking to master nodes.
Will bring up cluster
Drunkensmee needs to have $HOSTNAME passed as an env variable into the unit ssl template files.
