### ISSUE TITLE
KubeDNS modification path

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#869]
We should be able to modify the running deployment of kubedns with kraken-lib.  Currently we only set the versions for kubedns when creating a cluster.

**Comment by mikeln** [comment]
Running 'services' tag is probably too coarse, since it would include anything in charts also.  Probably should add a `dns` ansible tag that only runs services.dns.

**Comment by mikeln** [comment]
I still wonder if this isn't the real answer for some things: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/addon-manager

**Comment by leahnp** [comment]
As per @mikeln 's advice I am looking into the `addonmanager.kubernetes.io/mode: Reconcile` label.

**Comment by mikeln** [comment]
It would be good for us to really understand what the addon manager exactly does, and if it is "the way of the future" for this type of thing that is required for kubernetes to run.   My initial read last release, was that this was the idea, but in this dynamic arena...that may have changed.

**Comment by leahnp** [comment]
We had an enlightening conversation with @spiffxp and @mikeln and decided we probably shouldn't rely on addon manager at this point in its development. I will look into ansible tags, unless someone has an issue with that fix.

**Comment by leahnp** [comment]
@coffeepac are we only talking about kubeDNS version ie: gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.5 or all the kubeDNS dependencies (kubeDNS, dnsmasq & dnssidecar)?

**Comment by coffeepac** [comment]
all kubeDNS components.  

and I think an ansible tag that only recreates the dns deployment is great.

**Comment by leahnp** [comment]
@coffeepac am I on the right track designing this to be ran like: `docker run .... update.sh --dns`

**Comment by coffeepac** [comment]
second option.  dns_only ansible tag.
