### ISSUE TITLE
The curator should be able manage krakencrashreporter index messages.

### ISSUE THREAD

**Issue by oneilcin** [samsung-cnct/kraken-lib#871]
The "krakencrashreporter" index will be populated with a date (timestamp) when the PR's for crashbackend, and k2-crash-application new datetime index are merged.  These messages can contain kraken logs.  Curator should be able to manage reaping the old ones.

Note: Eventually we will delete the old "k2crashreporter" index when we are satisfied that there are no longer old kraken installs that we need to support.

**Comment by DStorck** [comment]
Currently curator uses an action called delete_indices to wipe out logs older than 14 days.   Most of our logs are given a logstash prefix, along with the date, that curator uses to determine age.  The krashreporter will need a custom action and filter to use the date field to wipe the logs instead.
this was a test filter I had written to use @timestamp that may be useful: 
```        filters:
        - filtertype: pattern
          kind: prefix
          value: logstash- (this would be changed to match new index)
          exclude: False
        - filtertype: age
          source: field_stats
          direction: older
          unit: days
          unit_count: 14
          field: '@timestamp'
          stats_result: min_value```

**Comment by coffeepac** [comment]
pat to move to issues/operations with ask that clusterops team install the chart with a correct configmap

**Comment by coffeepac** [comment]
moved.
