### ISSUE TITLE
Feature request: Cleanup "a_cluster" vs "cluster" fact references throughout kraken-lib

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/kraken-lib#874]
We have a lot of `with_items` tasks that include another file on a per-cluster basis. We set the loop_var to be `a_cluster`, for instance in kraken.fabric.selector/tasks/main.yaml: 
```- include: fabric-type.yaml
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when: a_cluster.providerConfig.type == 'cloudinit'
```
Then in the included file, the first task reads:
```
- name: Set cluster fact
  set_fact:
    cluster: "{{ a_cluster }}"
```

(In that particular example from the code base, we actually set `cluster` to `a_cluster` several times, which is extra unnecessary, but this pattern is repeated elsewhere.)

Since we are _explicitly_ setting a `loop_var` to `a_cluster` in every `include:` task, I would like to suggest just setting `loop var` to `cluster` which would eliminate the need to explicitly reassign `cluster` to refer to a previously passed `a_cluster`.

**Comment by joejulian** [comment]
This is because we use `set_fact:` tasks everywhere instead of using `vars:` with includes. As the fact is set, loop_var will balk if the var you're trying to use is a fact.
