### ISSUE TITLE
dryrun requires network access

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#882]
with the `terraform plan` commands, dryrun is now contacting aws and causes failures if disconnected from a network. Dryrun should not require network access.

**Comment by coffeepac** [comment]
do you have a suggestion for how we can exercise the terraform templates in a 'dry run' fashion without network access?

**Comment by joejulian** [comment]
I do not. I just discovered this as I was working with the templates while on a bus without activating my hotspot.

**Comment by philoserf** [comment]
`terraform plan` requires network/aws access. Perhaps we could introduce logic to test for that and halt with a user message.

**Comment by joejulian** [comment]
My preference would be to just bypass it on dryrun. Dryrun should not call out.

**Comment by philoserf** [comment]
So rather than halt we bypass/continue. Should we notify of a skipped step? That seems common for dry runs. For example, here is the result of `ansible-playbook check` which is a dry run.

```
TASK [Signing in to MAS] **********************************************************************************************
skipping: [127.0.0.1]
```

**Comment by coffeepac** [comment]
`terraform validate` is probably what we to use instead of plan then.

is there any value to executing plan as part of kraken-lib normal operations?  I think the etcd clusters will use the saved plan but I'm not sure what we gain by doing that.
