### ISSUE TITLE
Create Kraken Version of prometheus-operator

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/kraken-lib#884]
Sub-issue of #876 

Create a kraken specific version/deployment of: https://github.com/coreos/prometheus-operator
Using the full up working example provided by: https://github.com/camilb/prometheus-kubernetes/operator

This will require its own repo be created first.  (see corresponding issue).

Initial work has shown there are some namespace issues if the default "monitoring" namespace is not used.  That should be resolved so we can use something like "kube-monitor" or "kraken-monitor".
Also there are some specifics that should also be changed to make the source example more kraken (kraken-lib) friendly.

The deployment scripts should be set up to use a user provided kubeconfig and base directory (if applicable).   The deployment scripts should be implemented in terms of helm chart(s) if there is no blocking reason (such as startup timing). (See corresponding issue for that).

**Comment by mikeln** [comment]
See initial start: https://github.com/mikeln/kraken-monitor

**Comment by coffeepac** [comment]
move to issues
p1

**Comment by coffeepac** [comment]
moved to samsung-cnct/issues#78
