### ISSUE TITLE
Create Monitoring Setup for Etcd and Etcd Nodes

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/kraken-lib#885]
Sub-issue of #876

Using prometheus-operator and the corresponding initial setup as an example.
Create the needed prometheus node scraping needed for kraken etcd nodes.  Note, an example of this may exist somewhere in the kubernetes world.  Otherwise use the kubernetes node monitoring as a starting example (if possible).

Also, create the needed prometheus-operator service monitor service for each of the etcd clusters so they will be automatically added to the monitoring system.

**Comment by coffeepac** [comment]
p1, move to issues

**Comment by coffeepac** [comment]
moved to samsung-cnct/issues#79
