### ISSUE TITLE
Determine And Implement Best Way to Access Monitoring UIs

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/kraken-lib#886]
Sub-issue of #876

Determine the security requirements needed for the Monitoring UIs.
Such as, is `kubectl proxy-forward` adequate?  Or will we need a secured access Ingress?

Desired result is a well defined policy for access.

**Comment by coffeepac** [comment]
p1. to issues

**Comment by oneilcin** [comment]
A secure ingress seems like a desirable way to go for most users.  I will get input from cluster ops and Rick.

**Comment by coffeepac** [comment]
moved to samsung-cnct/issues#81
