### ISSUE TITLE
Enable Kraken Config Control of the Kubernetes Cluster ELB Timeout

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/kraken-lib#887]
Sub-issue of #876

If using `port-foward` is desired,  the communication is piped through kubectl via the main Kubernetes Service connection.   In AWS this is the default ELB created for the cluster.  The default idle timeout is 60 seconds, which is far too short for any type of long term monitoring UI.

Currently the only way to change the value of the Idle Timeout of that ELB is via the AWS console.   

It is desirable to set that timeout value via the kraken-lib config so it is set during the creation of the ELB.

**Comment by coffeepac** [comment]
moved to samsung-cnct/issues#82
