### ISSUE TITLE
Create Repo for Kraken Monitoring Solution

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/kraken-lib#888]
Sub-issue of #876

Create a repository for the Kraken Monitoring work.  
Setup and format TBD but some root pieces must be based on other kraken repos (from Solas setup).

**Comment by mikeln** [comment]
initial start of content.  missing solas setup: https://github.com/mikeln/kraken-monitor

**Comment by coffeepac** [comment]
p1

**Comment by coffeepac** [comment]
moved to samsung-cnct/issues#83
