### ISSUE TITLE
Determine Method of On-the-fly Alert Addition/Modification

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/kraken-lib#890]
Sub-issue of #876

Prometheus-operator contains alert routing etc. 
It also contains some basic alert set ups.  
However, we will want to add and perhaps change alert criteria/setup while the cluster is running.

Determine if this will be possible at all.  (it should be).

Determine the method to do this.  i.e.  Is kubectl apply  or helm update going to be viable?

Will we want to develop a small webapp/UI to make this configuration more user friendly?  If so a follow on issue will be needed for that development.

**Comment by mikeln** [comment]
https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/alerting.md
https://prometheus.io/docs/alerting/configuration/

**Comment by coffeepac** [comment]
moved to samsung-cnct/issues#80
