### ISSUE TITLE
Investigate whether GKE config file needs to make fabric references

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/kraken-lib#899]
We do not use fabric for GKE clusters, yet the definitions exist in the GKE config file shipped with kraken-lib.

- Decide if there are any good reasons to keep fabric definition in the GKE config file
- make changes accordingly
- adjust schema to allow for these changes if necessary

**Comment by oneilcin** [comment]
We don't?  Wah I just spent time testing this for the fabric upgrades.
