### ISSUE TITLE
add option to install helm registry apps in config by channel

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/kraken-lib#900]
currently in helmConfigs, we give the user an option to specify the version of the chart they'd like, which we pass to `--version` in `run-services.yaml` .  
Now that we are using quay to host our charts, the user has the option of specifying a channel instead, such as :stable.  
(referenced [here](https://github.com/app-registry/appr-helm-plugin/issues/33#issuecomment-316948557))
Do we want to include this option in helmConfigs?  Yes

**Comment by coffeepac** [comment]
fixed by #1033
