### ISSUE TITLE
[Up issue] seeing error with dns_only flag

### ISSUE THREAD

**Issue by alejandroEsc** [samsung-cnct/kraken-lib#904]
So when running kraken-CI, with kraken, i have found these errors:

```
[gke] TASK [roles/kraken.services : set cluster fact] ********************************
[gke] fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check '(kraken_action == 'up') and not ( dns_only | bool )' failed. The error was: error while evaluating conditional ((kraken_action == 'up') and not ( dns_only | bool )): 'dns_only' is undefined\n\nThe error appears to have been in '/kraken/ansible/roles/kraken.services/tasks/run-services.yaml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: set cluster fact\n  ^ here\n"}
```

my suspicion is that the file found in ansible/roles/kraken.config/defaults/main.yaml which has

dryrun: false

also needs 

dns_only: false 

BUT this is a crutch the real issue is the bash and needs to be fixed there.

**Comment by guineveresaenger** [comment]
Correction for filepath:
ansible/roles/kraken.config/defaults/main.yaml
(it's not in the main tasks file)

**Comment by alejandroEsc** [comment]
@guineveresaenger thanks for the correction :)

**Comment by coffeepac** [comment]
I'm going to do this now.  its a blocker for getting a 1.8 conformance PR up.

**Comment by guineveresaenger** [comment]
I just did

**Comment by alejandroEsc** [comment]
@guineveresaenger can you link here?

**Comment by guineveresaenger** [comment]
one sec

**Comment by guineveresaenger** [comment]
https://github.com/samsung-cnct/kraken-lib/pull/905

**Comment by coffeepac** [comment]
this is fixed.
