### ISSUE TITLE
gke config file generation

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#926]
`kraken-lib` will only generate the aws config file.  we have a default gke file and we allow users to specify gke as a type in `kraken`.  allow this to be specified in kraken-lib as well.

make sure docs get updated, should be the getting started readme.

**Comment by leahnp** [comment]
I initially wanted to try and imitate kraken with: `$ ./bin/up.sh --generate --provider GKE`
But since we are parsing this in bash, I think it might be overly complicated.

Should I opt for using `KRAKEN_TAGS` instead? IE: `$ ./bin/up.sh --generate KRAKEN_TAGS=GKE`

@coffeepac
