### ISSUE TITLE
password protected ssh keys

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken-lib#927]
if a user attempts to use an password protected ssh key, ansible will ask for user input.  This is a problem when using `kraken` as the process simply blocks waiting for input that will never come.

kraken-lib should explicitly not support password protected ssh keys.  documentation should updated to reflect this.  kraken-lib should detect such a key and fail out.

**Comment by davidewatson** [comment]
I would go further and suggest that `kraken-lib` should attempt to avoid depending on ssh keys at all. Currently `ansible/roles/kraken.provider/kraken.provider.aws/tasks/wait-for-one-etcd.yaml` is the only place where we depend on ssh keys, and I have designs to remove the usage there.

ssh is an important tool in an SRE's arsenal when things go wrong, but it should not be required for normal operation. I think it may be unnecessary for standing up the cluster too.
