### ISSUE TITLE
Create flag to disable K8s cluster-autoscaling

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/kraken-lib#936]
Related to: https://github.com/samsung-cnct/kraken-lib/issues/150

Create a flag to allow kraken users to return to desired `node.count` by *disabling cluster-autoscaling* (which should have been added to our default config in the above issue). The flag should be passed to `update.sh` and scale up or down cluster to desired `node.count` and disable cluster-autoscaling. 

This flag will need to account for resource recovery. IE: if a cluster is at a maxNodes of 10 as per the [cluster-autoscaler addon](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler), but the desired node count is 4, this flag will need to "properly" drain 6 nodes, reschedule resources and remove the nodes. Note "properly" is in quotes because it is TBD - there are a lot of edge cases to consider. 

There should be a design proposal for this and team involvement to document this tricky task of removing production nodes with running resources.

**Comment by davidewatson** [comment]
My preference would be to handle this entirely within the config file. Our past attempts at adding out of band configuration information (e.g. the HELM_OVERRIDE env var) have only lead to confusion. Maybe I am alone here.

Idea! If a user wants to change the ASG without documenting it in the config file (something which I think is a poor idea), they can always do so through the AWS web interface.

**Comment by davidewatson** [comment]
Better idea? We should open an issue against the cluster-auto scaler to implement this feature. This would keep the division of responsibilities clear.
