### ISSUE TITLE
Create cloud-init (standard, not coreos) user-data for ubuntu (and potentially others)

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#937]
CoreOS uses a non-standard cloud-init which is implemented (mostly) in `cloud_config/units.yaml` and a few other entries that are coreos specific. By creating another parallel implementation of `cloud_config/units.yaml` and adding conditionals for the coreos specific items, we can take the same source data and create output that will work with the standard cloud-init.

**Comment by joejulian** [comment]
PR #965

**Comment by leahnp** [comment]
LGTM
