### ISSUE TITLE
Document a minimal method by which a bare-metal cluster can be brought up 

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#939]
Kraken does not yet have bare-metal support. Document a way in which a functional cluster can be created with a combination of kraken and manual steps.

**Comment by coffeepac** [comment]
Expected process (details to be ironed out while testing):
- (manual) create MAAS "pod" that has a private network (assume 10.0.0.0/8 for now)
- (manual) assign 5 nodes to this pod
- (manual) label nodes as etcd (1), master (1), worker (3)
- (?) generate cloud_config files
  - one of:  manual template to fill out, scripted template to execute, kraken tag
  - required output: CA directory
- (?) allocate, deploy etcd node and grab ip
  - one of: script, kraken tag
  - required output: ip of node
- (?) allocate, deploy master node using etcd ip
  - one of: script, kraken tag
  - required output: ip of node
- (?) allocate, deploy worker nodes using master ip
  - one of: script, kraken tag
- (kraken) configure kubernetes cluster using master ip and CA directory

**Comment by countspongebob** [comment]
Looks like what we discussed on the board. Needs expansion, though.

**Comment by coffeepac** [comment]
@countspongebob first cut with expansion

Expected process (details to be ironed out while testing):

  The first several steps to creating a kraken managed kubernetes cluster in MAAS 
are manual and can probably be handled entirely from the MAAS GUI.  We will not go 
into detail here about how to perform these actions as the operator is assumed to 
be knowledgable about MAAS.
  1. Create a new "pod" in MAAS.  This pod should have its own private network space,
  preferably a full 10.0.0.0/8 block.  Nodes in this pod will need access to the 
  internet at large to download images.  
  2. Assign 5 nodes to this pod.  All nodes should have at least 2 cores an 4GB of 
  memory, more is fine.
  3. Label the five nodes as:
    - etcd (x1)
    - master (x1)
    - worker (x3)

  The next step will be using kraken-lib directly to generate the cloud config files.
The exact incantation will be provided later but it will look something like:
  `docker run -v <volumes> -e EXTRA_VARS=<specific vars> quay.io/samsung_cnct/kraken-lib:v0.11 /bin/up.sh --tags cloud-config-only`

This command will produce an output directory that contains, among other things,
a diretory named `cloud-config` that contains the cloud config files.  It will
also create a directory named `ca` that contains SSL certificate information 
that is necessary for secure intra-cluster communications.  Please make a note of
the full path to both of these directories.
  The next step will use a bash script that will call several sub programs.  Each
sub program will provision a single type of kubernetes node in MAAS:  etcd, master 
or worker.  This bash script may need to be edited to include the full path to the
cloud-config directory.  This bash script will have two important outputs:
  1. five nodes in MAAS that have all necessary components installed to become a
  kubernetes cluster
  2. the ip address of the master node.  We will need this ip address in the next
  step.
  The final step is to make a call to `kraken` to finish the configuration of the
provisioned kubernetes cluster.  You will need to run something very similar to the
cloud-config generation step, such as:
  `docker run -v <volumes> -e EXTRA_VARS=<specific vars> quay.io/samsung_cnct/kraken-lib:v0.11 /bin/up.sh --tags configure-provisioned-cluster`

This command will perform all actions necessary to configure the kubernetes cluster.

We may make this process simpler if there is a straightforward way to group all of
the non-manual steps into a single script.  This script would be composed of the
steps that are listed but as a convenience we may wrap them all up if we can.  We may also
have to add additional scripted steps to make the non-manual portions as user-friendly
as possible.

**Comment by coffeepac** [comment]
@lostlivio the above doc is for you to review as well.  seem sane?

**Comment by lostlivio** [comment]
@coffeepac makes sense.  The comment, "as the operator is assumed to
be knowledgable about MAAS.".  Has this expectation been communicated previously by Bob or are we just assuming this?

**Comment by lostlivio** [comment]
@coffeepac I clarified with @countspongebob...We need to provide an opinionated setup and directions for MAAS as well and we shouldn't assume they will be knowledgable in this.

**Comment by coffeepac** [comment]
I am specifying an opinionated setup.  It will take me a few days to get MAAS configuration directions together, I would need to sort it out first myself.

As a first cut can we leave the detailed steps out and say we will provide the steps necessary with the full doc?

As an aside, I am somewhat nervous about specifying the MAAS steps as we will be interacting with their MAAS configs and their network.  We may not have a complete picture for that, hence why I was describing a desired end state, rather then the process to there.

**Comment by coffeepac** [comment]
@lostlivio I was way off on what a Pod in MAAS is.  It is not an analog to a VPC, its something else entirely.  These instructions need some re-writing.

**Comment by countspongebob** [comment]
A pod is a group of machines. Probably a highly useful notion in a larger environment, but can be put off. Our instructions should work in our NUC lab, and we should help them debug it in theirs once we do.

**Comment by coffeepac** [comment]
@countspongebob, @lostlivio  second cut.  only change is in MAAS directions.  I simplified them.

Expected process (details to be ironed out while testing):

  The first several steps to creating a kraken managed kubernetes cluster in MAAS 
are manual and can probably be handled entirely from the MAAS GUI.  We will provide
exact directions for these steps with the full directions later.
  1. Allocate 5 nodes for kubernetes.  All nodes should have at least 2 cores an 4GB of 
  memory, more is fine.
  2. Label the five nodes as:
    - etcd (x1)
    - master (x1)
    - worker (x3)

  The next step will be using kraken-lib directly to generate the cloud config files.
The exact incantation will be provided later but it will look something like:
  `docker run -v <volumes> -e EXTRA_VARS=<specific vars> quay.io/samsung_cnct/kraken-lib:v0.11 /bin/up.sh --tags cloud-config-only`

This command will produce an output directory that contains, among other things,
a diretory named `cloud-config` that contains the cloud config files.  It will
also create a directory named `ca` that contains SSL certificate information 
that is necessary for secure intra-cluster communications.  Please make a note of
the full path to both of these directories.
  The next step will use a bash script that will call several sub programs.  Each
sub program will provision a single type of kubernetes node in MAAS:  etcd, master 
or worker.  This bash script may need to be edited to include the full path to the
cloud-config directory.  This bash script will have two important outputs:
  1. five nodes in MAAS that have all necessary components installed to become a
  kubernetes cluster
  2. the ip address of the master node.  We will need this ip address in the next
  step.
  The final step is to make a call to `kraken` to finish the configuration of the
provisioned kubernetes cluster.  You will need to run something very similar to the
cloud-config generation step, such as:
  `docker run -v <volumes> -e EXTRA_VARS=<specific vars> quay.io/samsung_cnct/kraken-lib:v0.11 /bin/up.sh --tags configure-provisioned-cluster`

This command will perform all actions necessary to configure the kubernetes cluster.

We may make this process simpler if there is a straightforward way to group all of
the non-manual steps into a single script.  This script would be composed of the
steps that are listed but as a convenience we may wrap them all up if we can.  We may also
have to add additional scripted steps to make the non-manual portions as user-friendly
as possible.

**Comment by joejulian** [comment]
> This bash script may need to be edited to include the full path to the
cloud-config directory.

This will be predictable using the standard output paths and filenames that we currently use based on the cluster name.

**Comment by coffeepac** [comment]
@joejulian I imagine that we'll give them something that does the config generation and then we can package up all of the non-MAAS steps into a single shell script.  Hence the 'may', we 'may' not get there.

**Comment by coffeepac** [comment]
@lostlivio https://github.com/samsung-cnct/maas-handrolled/pull/1

can you give this a try and if it works lets ship it.

**Comment by coffeepac** [comment]
@lostlivio I believe this is completely done and you've sent it off to HQ.  I'm going to close this issue for now.  if there is more work to be done we can re-open it and get back to it.
