### ISSUE TITLE
Fail gracefully if Helm chart already exists

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/kraken-lib#949]
If you run `up.sh` on an exiting cluster with the flag `services_only` kraken will fail on:
`TASK [roles/kraken.services : Install charts from registry]` and potentially (I have not tested this one, but I assume it would show the same behavior): `TASK [roles/kraken.services : Install charts from repo]`

An example of the error is: 
   ``` "stderr": "usage: appr [-h]\n            {pull,run-server,show,inspect,list,delete-package,helm,version,logout,deploy,plugins,push,login,config,channel,jsonnet}\n            ...\nappr: error: \nmessage: 'Error: a release named heapster already exists.\n\n  Run: helm ls --all heapster; to check the status of the release\n\n  Or run: helm del --purge heapster; to delete it\n\n  '\n\nError: plugin \"registry\" exited with error"```

We should either ignore these errors and keep running the script or use a conditional check to see if the Helm package already exists before trying to install.

**Comment by DStorck** [comment]
if we are going to ignore the errors, then we should spit out some sort of message at the end so the user doesn't think their charts went up as planned.

**Comment by joejulian** [comment]
imho we should `helm [registry] upgrade --install` which will succeed either way.

**Comment by coffeepac** [comment]
because we are running tiller in a kraken namespace we should always do as @joejulian commented.
