### ISSUE TITLE
Update ancient kubedns defaults

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/kraken-lib#952]
In https://github.com/samsung-cnct/kraken-lib/blob/master/ansible/roles/kraken.services/defaults/main.yaml, there are still some k8s 1.5 references, which results in us using a really ancient version of kubedns.

Here are the  versions being used upstream on k8s, on kraken, and on latest kube-dns
Tested: 1.14.7
Kraken: 1.14.5 (k8s 1.6); 1.8 (default), 1.9 (k8s 1.5, which is unsupported)
Latest: 1.14.7

Default should be 1.14.5, to conform with upstream tested version.

**Comment by coffeepac** [comment]
this was done.
