### ISSUE TITLE
Confusing message on `kraken cluster down`

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/kraken-lib#955]
When running `kraken cluster down` on a GKE cluster, the following output is displayed.

```$ kraken cluster down
Using Kraken config file: /Users/lpetersen/.kraken/config.yaml 
Pulling image 'quay.io/samsung_cnct/k2:v0.5' █▒▒▒▒▒▒▒▒▒ Complete
Bringing down cluster 'lp-gke' █████▒▒▒▒▒ Complete
Done.
Some of the cluster state MAY be available:
```

The message `Some of the cluster state MAY be available` is confusing when running `down`. It seems this message should only be displayed in the event of a failure on `up` or `update` and different language should be used if there is a failure on `down`. 

Beyond the confusing language, I don't understand why this function `show_post_cluster_error` would be called on a successful `kraken cluster down` run.

**Comment by coffeepac** [comment]
@leahnp to move to kraken, same labels.  please add to board.

**Comment by leahnp** [comment]
Closed in favor of: https://github.com/samsung-cnct/kraken/issues/214
