### ISSUE TITLE
Remove --network-plugin-dir argument from kubelet

### ISSUE THREAD

**Issue by venezia** [samsung-cnct/kraken-lib#969]
The command line argument `--network-plugin-dir` has been removed from kubelet starting with v1.7 [v1.7](https://v1-7.docs.kubernetes.io/docs/admin/kubelet/) vs [v1.6](https://v1-6.docs.kubernetes.io/docs/admin/kubelet/)

Starting in v1.9, this causes kubelet to be unable to come up.

Impacted files:

* ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/units.kubelet.part.jinja2
* ansible/roles/kraken.nodePool/kraken.nodePool.master/templates/v1.7/units.kubelet.part.jinja2
* ansible/roles/kraken.nodePool/kraken.nodePool.node/templates/units.kubelet.part.jinja2
* ansible/roles/kraken.nodePool/kraken.nodePool.node/templates/v1.7/units.kubelet.part.jinja2

**Comment by coffeepac** [comment]
this is done.
