### ISSUE TITLE
Kubernetes 1.9 Changes Tracking Issue (kraken-lib & kraken-tools)

### ISSUE THREAD

**Issue by oneilcin** [samsung-cnct/kraken-lib#978]
1.  Change the etcd version to match kubernetes 1.9 conformance testing.
As of Nov 17th, they've been testing with Etcd 3.1.10 in [this link](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-etcd3/16512/artifacts/nodes.yaml)
The [sig scale notes](https://docs.google.com/document/d/1hEpf25qifVWztaeZPFmjNiJvPo-5JX1z0LSvvVY5G2g/edit#heading=h.ukbaidczvy3r)  talk about the etcd version for 1.9

2. Check for the kubernetes tested version of kube-dns to see if it changed for this release.
Tips for looking. https://k8s-testgrid.appspot.com/ 
Select 'sig-scalability' -> 'sig-scalability-gce' -> 'gce-1.9' ->About (see these results in Gubernater) -> choose a green build -> Artifacts -> Artifacts folder -> scroll down to nodes.yaml

**Comment by coffeepac** [comment]
going to start working on this now.

**Comment by coffeepac** [comment]
calico upgrade is going to be a bit of a bother.  we need to ensure the 2.6 version is at least 2.6.5 before moving to 3.0.1 (do not use 3.0.0).

**Comment by coffeepac** [comment]
rbac and a bunch of app types (daemonset in particular) have gone GA so there are a lot of template/file changes based on version.  so many more files :(

**Comment by coffeepac** [comment]
all etcd reads now require a successful quorum read.  this is a note to self.

**Comment by coffeepac** [comment]
first attempt with a 1.9 cluster.  it is predictably not working.  lets find out why!

**Comment by coffeepac** [comment]
second attempt is failing when attempting to install the network fabric.  neat!  progress!

**Comment by coffeepac** [comment]
branch:  https://github.com/coffeepac/kraken-lib/tree/kubernetes-1.9

**Comment by coffeepac** [comment]
project canal doesn't support canal 3.x on kubernetes yet, reverting to 2.6.2.

**Comment by coffeepac** [comment]
got a valid 1.9 cluster running.  setting sonobuoy loose to see what it comes up with.  if it passes I'll push a PR.

**Comment by coffeepac** [comment]
log output from e2e as run by sonobuoy.

[e2e.log](https://github.com/samsung-cnct/kraken-lib/files/1592036/e2e.log)

**Comment by coffeepac** [comment]
now to make 1.7 and 1.8 still work.

**Comment by coffeepac** [comment]
one last open question on the PR, after that this is done.  Putting into review.
