### ISSUE TITLE
GKE ssh instructions, not working

### ISSUE THREAD

**Issue by oneilcin** [samsung-cnct/kraken-lib#979]
I brought up a GKE cluster that had 12 nodes (4 in 3 regions)

The output on a successful up, gave me ssh commands for 4 nodes.
```To ssh:

    ssh -F /Users/cynthiaoneill/.kraken/cindygke-nov18/ssh_config clusternodes-1
    ssh -F /Users/cynthiaoneill/.kraken/cindygke-nov18/ssh_config clusternodes-2
    ssh -F /Users/cynthiaoneill/.kraken/cindygke-nov18/ssh_config othernodes-1
    ssh -F /Users/cynthiaoneill/.kraken/cindygke-nov18/ssh_config othernodes-2
```
Following the ssh instructions doesn't work.  I was able to ssh using the GCP Console.

**Comment by davidewatson** [comment]
I have not tested gke, but you should be able to run `KRAKEN_TAGS=ssh_only ./bin/up.sh --config ~/.kraken/config.yaml` to regenerate the `ssh_config`.
