### ISSUE TITLE
migrate to gitlab

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/kraken-lib#989]
remove jenkinsfile and have CI run on gitlab
when complete, please check off `kraken-lib` on https://github.com/samsung-cnct/issues/issues/89#issuecomment-343000090

**Comment by venezia** [comment]
Would the Jenkinsfile be useful to other people?  It might not be worth removing, but we might want to indicate that it is not currently maintained.

**Comment by philoserf** [comment]
Unused files are poison. It is still there in history. If we want it as information then a code block in a MD file makes sense.

\`\`\`plain
...
\`\`\`

**Comment by leahnp** [comment]
Waiting on runner memory increase to accommodate E2E test.

**Comment by leahnp** [comment]
Working on build/publish stages today, still waiting on resolution with memory increase.
