### ISSUE TITLE
Generated config should be complete with some default cluster name

### ISSUE THREAD

**Issue by philoserf** [samsung-cnct/kraken-lib#995]
**Is this a BUG REPORT or FEATURE REQUEST?**:

FEATURE REQUEST

**Kraken version**:

1.2.3-stable+git.sha.f855e5378bcf1d80ffbf441b8274e145cec1ce2e

**What happened**:

After running `./bin/up.sh --generate` the config MUST be edited before it can be used.

**What you expected to happen**:

Running `./bin/up.sh --generate` could produce a complete configuration with a required value for the cluster name.

**Anything else we need to know**:

Also reported at samsung-cnct/kraken#220

**Comment by joejulian** [comment]
To avoid the problems we had before we removed a default name, the name could be generated using the "combined word" strategy used by kubernetes for things like pod naming, ie. "understated-octopus".

**Comment by philoserf** [comment]
The strategy could also be a constructed pseudo random value like default-$(date "+%y%m%d")-$USER
